// Alexander the Great, 334–323 BC: the conquest of the Persian Empire, from the Hellespont to the Indus.
const INDIA = ['taxila', 'hydaspes', 'hyphasis'];

export default {
  id: 'alexander', n: 3, era: 'The ancient world', age: 'ancient',
  title: 'Alexander', years: '334–323 BC',
  you: 'macedon',
  hero: { name: 'Alexander', title: 'King of Macedon', look: 'hellenic' },
  advisor: { name: 'Parmenion', title: 'your father’s old general', look: 'hellenic' },
  court: [{ id: 'parmenion', name: 'Parmenion', title: 'your father’s old general', look: 'hellenic', until: 7 }, { id: 'hephaestion', name: 'Hephaestion', title: 'your dearest friend', look: 'hellenic', until: 13 }, { id: 'craterus', name: 'Craterus', title: 'the soldiers’ favourite', look: 'hellenic', from: 8, until: 13 }, { id: 'perdiccas', name: 'Perdiccas', title: 'commander of the Companions', look: 'hellenic', from: 14 }],
  hook: 'Twenty-two years old, you cross into Asia to take the greatest empire on earth.',
  art: 'expedition',
  brief: [
    'Spring 334 BC. Your father Philip made Macedon master of Greece and was murdered before he could invade Persia. You are Alexander, twenty-two years old, and the Greek cities have named you their general against the Great King.',
    'You cross the Hellespont with about 37,000 men and little money. Persia has millions of subjects, a great fleet that rules the Aegean, and Darius III. Your army is the finest in the world: the phalanx with its long pikes, and your Companion cavalry.',
  ],
  goal: { kind: 'take', provs: ['babylon', 'susa', 'persepolis', 'ecbatana', 'bactra', 'taxila'], text: 'Take the royal cities of Persia, and march on to the Indus', won: 'The Persian Empire is yours, from the Aegean to the Indus' },
  lose: { hero: 'Alexander has fallen, and his army breaks up', will: 'Your Macedonians will follow you no further: the army mutinies and goes home', capital: 'Macedon itself has fallen behind you' },
  history: {
    won: true, at: 12,
    text: 'Alexander won everything. He beat the Persians at the Granicus, Issus and Gaugamela, took Babylon, Susa and Persepolis, and hunted down Darius’s killers to the edge of Central Asia. In 326 BC he crossed into India and beat King Porus at the Hydaspes, but his army refused to march further. He died in Babylon in 323 BC, aged 32, and his generals tore his empire apart.',
    better: 'Do it in less time than Alexander did.',
  },
  view: [23.5, 19.0, 43.5, 77.0],
  goldPer: 5,
  reach: 260,
  turns: ['Spring 334 BC', 'Autumn 334 BC', 'Spring 333 BC', 'Autumn 333 BC', 'Summer 332 BC', 'Spring 331 BC', 'Autumn 331 BC', 'Spring 330 BC', 'Autumn 330 BC', 'Summer 329 BC', 'Summer 328 BC', 'Spring 327 BC', 'Spring 326 BC', 'Autumn 325 BC', 'Summer 323 BC'],
  meanwhile: [
    'Alexander crosses the Hellespont with about 37,000 men. At the river Granicus he charges at the head of his Companion cavalry and breaks the army of the Persian satraps.',
    'Miletus falls after a siege. Halicarnassus holds out for months under Memnon of Rhodes, the ablest Persian commander, before its defenders slip away by sea.',
    'At Gordium Alexander undoes the famous knot. Memnon, carrying the war to the Aegean islands with the Persian fleet, dies of an illness.',
    'Darius III comes down on Alexander’s rear at Issus. In the narrow plain by the sea Alexander charges straight at the king, who flees, leaving his mother, wife and daughters behind.',
    'Tyre, on its island, holds out for seven months until Alexander builds a causeway to it and storms the walls. Gaza falls after two months more.',
    'Egypt welcomes Alexander as a liberator. He founds Alexandria and crosses the desert to the oracle of Ammon at Siwa.',
    'At Gaugamela, on 1 October 331 BC, Alexander defeats Darius’s great army, and Darius flees again. Babylon and Susa open their gates.',
    'Alexander forces the Persian Gates and takes Persepolis, the royal city, and its palace burns. In Greece, Antipater has crushed a Spartan revolt at Megalopolis.',
    'Darius is murdered by his own satrap Bessus, who calls himself king. Alexander begins to wear Persian dress; his general Parmenion is put to death.',
    'Alexander crosses the Hindu Kush into Bactria. Bessus is handed over and executed. Alexander founds a city on the Jaxartes, the edge of his world.',
    'Spitamenes leads Sogdiana in revolt. At a drunken feast in Maracanda Alexander kills his friend Cleitus, who had saved his life at the Granicus.',
    'Alexander takes the Sogdian Rock and marries Roxana, a Sogdian noble’s daughter. Then he marches for India.',
    'At the Hydaspes river Alexander defeats King Porus and his war elephants, and makes him his ally. At the Hyphasis his army refuses to go further, and he turns back.',
    'Half the army goes home through the Gedrosian desert, where thousands die of thirst and heat.',
    'Alexander dies in Babylon in June 323 BC, aged 32, of a fever or, some said, of poison. His generals divide his empire.',
  ],
  sides: {
    macedon: { name: 'Macedon', heirs: ['Perdiccas'], color: '#7d1f2b', leader: 'Alexander', capital: 'pella', gold: 70, will: 78, quality: 1.35, horse: 0.25, fleet: 0, levy: 9000, income: 25, speed: 3, tech: ['hoplites'], weariness: 1.1, persona: 'Alexander of Macedon, who believes he is destined to rule Asia.' },
    persia: { name: 'The Persian Empire', short: 'Persia', heirs: ['Bessus'], color: '#b3852c', leader: 'King Darius III', capital: 'babylon', gold: 500, will: 75, quality: 0.7, horse: 0.35, fleet: 3, levy: 6000, income: 10, ai: 'bold', weariness: 0.4, noPeace: true, persona: 'Darius III, King of Kings: brave enough, but no general, served by proud satraps who do not always agree.' },
    greeks: { name: 'The League of Corinth', short: 'Greek allies', color: '#27466e', leader: 'Athens and the allied cities', capital: 'athens', gold: 60, will: 40, quality: 1.1, horse: 0.05, levy: 2000, tech: ['hoplites'], ai: 'cautious', persona: 'The Greek cities: Alexander’s allies by oath, not by love.' },
    sparta: { name: 'Sparta', color: '#9c2a1c', leader: 'King Agis III', capital: 'sparta', gold: 40, will: 60, quality: 1.25, horse: 0.03, levy: 3000, tech: ['hoplites'], ai: 'bold', persona: 'Agis III of Sparta, who refused to join Alexander and waits for his chance.' },
    sogdians: { name: 'Sogdiana', color: '#5d7f86', leader: 'Spitamenes', capital: 'maracanda', gold: 40, will: 70, quality: 0.85, horse: 0.6, levy: 5000, ai: 'cunning', persona: 'Spitamenes, a Sogdian noble and horseman who fights from the steppe and never stands still.' },
    taxila: { name: 'Taxila', color: '#c2541f', leader: 'King Ambhi', capital: 'taxila', gold: 60, will: 40, quality: 0.9, horse: 0.15, levy: 4000, ai: 'cautious', persona: 'Ambhi, King of Taxila, who would rather befriend Alexander than fight him, and hates Porus.' },
    porus: { name: 'The Paurava kingdom', short: 'Porus', color: '#2b7d7a', leader: 'King Porus', capital: 'hydaspes', gold: 80, will: 70, quality: 1.05, horse: 0.2, levy: 8000, ai: 'steady', persona: 'Porus, a giant of a king with war elephants, who asks only to be treated as a king.' },
  },
  provinces: [
    ['pella', 'Pella', 40.76, 22.52, 'macedon', 2, 3],
    ['thrace', 'Amphipolis', 40.82, 23.85, 'macedon', 1, 2],
    ['sestos', 'Sestos', 40.23, 26.4, 'macedon', 0, 1],
    ['athens', 'Athens', 37.97, 23.73, 'greeks', 2, 4],
    ['sparta', 'Sparta', 37.07, 22.43, 'sparta', 0, 2],
    ['granicus', 'The Granicus', 40.23, 27.25, 'persia', 0, 1, { terrain: 'river' }],
    ['sardis', 'Sardis', 38.49, 28.04, 'persia', 2, 4, { treasure: 100 }],
    ['miletus', 'Miletus', 37.53, 27.28, 'persia', 2, 3],
    ['halicarnassus', 'Halicarnassus', 37.04, 27.42, 'persia', 3, 2],
    ['gordium', 'Gordium', 39.65, 31.98, 'persia', 1, 2],
    ['cilicia', 'Tarsus', 36.92, 34.89, 'persia', 1, 2],
    ['issus', 'Issus', 36.84, 36.2, 'persia', 0, 1, { narrows: true }],
    ['damascus', 'Damascus', 33.51, 36.29, 'persia', 1, 3, { treasure: 150 }],
    ['tyre', 'Tyre', 33.27, 35.2, 'persia', 3, 3],
    ['gaza', 'Gaza', 31.5, 34.47, 'persia', 2, 2],
    ['memphis', 'Memphis', 29.85, 31.25, 'persia', 1, 5, { treasure: 120 }],
    ['thapsacus', 'Thapsacus', 35.95, 38.4, 'persia', 0, 1, { terrain: 'river' }],
    ['gaugamela', 'Gaugamela', 36.57, 43.44, 'persia', 0, 1, { terrain: 'plains' }],
    ['babylon', 'Babylon', 32.54, 44.42, 'persia', 2, 6, { treasure: 250, garrison: 10000 }],
    ['susa', 'Susa', 32.19, 48.25, 'persia', 2, 5, { treasure: 350 }],
    ['gates', 'The Persian Gates', 30.6, 51.7, 'persia', 0, 0, { terrain: 'mountains', narrows: true }],
    ['persepolis', 'Persepolis', 29.93, 52.89, 'persia', 2, 5, { treasure: 450 }],
    ['ecbatana', 'Ecbatana', 34.8, 48.52, 'persia', 2, 4, { treasure: 150 }],
    ['rhagae', 'Rhagae', 35.59, 51.43, 'persia', 1, 2],
    ['parthia', 'Hecatompylos', 36.2, 54.15, 'persia', 0, 1],
    ['carmania', 'Carmania', 30.28, 57.08, 'persia', 0, 1, { terrain: 'desert' }],
    ['aria', 'Artacoana', 34.35, 62.2, 'persia', 1, 2],
    ['arachosia', 'Arachosia', 31.62, 65.71, 'persia', 1, 2],
    ['gedrosia', 'Gedrosia', 27.2, 62.3, 'persia', 0, 0, { terrain: 'desert' }],
    ['bactra', 'Bactra', 36.76, 66.9, 'persia', 2, 4],
    ['maracanda', 'Maracanda', 39.65, 66.96, 'persia', 1, 3],
    ['kapisa', 'Kapisa', 35.0, 69.25, 'persia', 0, 1, { terrain: 'mountains' }],
    ['taxila', 'Taxila', 33.74, 72.79, 'taxila', 2, 4],
    ['hydaspes', 'The Hydaspes', 32.93, 73.73, 'porus', 0, 2, { terrain: 'river' }],
    ['hyphasis', 'The Hyphasis', 31.6, 75.2, 'porus', 0, 2, { terrain: 'river' }],
  ],
  straits: [['sestos', 'granicus']],
  sea: [['athens', 'miletus']],
  armies: [
    ['macedon', 'sestos', 37000, 'Alexander', 5, { hero: true, id: 'alexander' }],
    ['macedon', 'pella', 12000, 'Antipater', 4, { id: 'antipater', stay: true }],
    ['persia', 'granicus', 35000, 'the satraps', 3, { id: 'satraps', temper: 'rash' }],
    ['persia', 'babylon', 70000, 'Darius III', 2, { id: 'darius', stay: true }],
    ['persia', 'halicarnassus', 8000, 'Memnon of Rhodes', 4, { id: 'memnon', stay: true }],
    ['persia', 'memphis', 6000, 'Mazaces', 2, { id: 'mazaces', stay: true }],
    ['persia', 'bactra', 20000, 'Bessus', 3, { id: 'bessus', stay: true }],
    ['sparta', 'sparta', 10000, 'Agis III', 3, { id: 'agis', stay: true }],
    ['greeks', 'athens', 6000, 'the Athenians', 2, { id: 'athenians', stay: true }],
    ['taxila', 'taxila', 10000, 'Ambhi', 2, { id: 'ambhi', stay: true }],
    ['porus', 'hydaspes', 35000, 'Porus', 4, { id: 'porus', stay: true }],
  ],
  wars: [['macedon', 'persia'], ['taxila', 'porus']],
  allies: [['macedon', 'greeks']],
  cards: [
    {
      id: 'granicus', at: 0, title: 'The river Granicus', art: 'battle',
      text: 'The Persian satraps wait on the far bank of the Granicus, their horsemen lined along the steep bank. It is late in the day. Old Parmenion advises camping and crossing at dawn, when the enemy will not expect it.',
      options: [
        { label: 'Cross at once and charge', fx: { morale: 12 }, hint: 'Strike while your men burn to fight; you will lead the Companions yourself' },
        { label: 'Wait for the dawn', fx: { men: 2000 }, hint: 'A rested army, and stragglers caught up' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander attacked at once: “The Hellespont would be ashamed if we feared this little stream.” He led the charge himself and was nearly killed; Cleitus the Black cut off the arm of the Persian about to strike him. The satraps’ army broke.',
    },
    {
      id: 'knot', at: 2, if: (q) => q.owns('macedon', 'gordium') || q.at('macedon', 'gordium') || q.near('macedon', 'gordium'), title: 'The Gordian knot', art: 'court',
      text: 'In the old Phrygian capital stands an ox-cart tied with a knot no one can undo. It is said that whoever loosens it will rule Asia. Your soldiers are watching.',
      options: [
        { label: 'Cut it with your sword', fx: { will: 8 }, hint: 'Your men will believe you were born to rule Asia' },
        { label: 'Leave the knot alone', fx: {}, hint: 'A king need not play at riddles' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander undid the knot, by cutting it with his sword according to most stories, or by drawing out the pin that held it. Either way, his men believed the prophecy was his.',
    },
    {
      id: 'letter', from: 3, until: 6, if: (q) => q.great() >= 1 && q.alive('persia'), title: 'A letter from Darius', art: 'peace',
      text: 'Darius offers you every land west of the Euphrates, ten thousand talents of gold and his daughter’s hand in marriage, if you will make peace. Parmenion says: “I would accept, were I Alexander.”',
      options: [
        { label: 'Refuse: Asia is not for sharing', fx: { will: 6 }, hint: '“So would I, were I Parmenion”' },
        { label: 'Accept half an empire', fx: { end: 'lose', why: 'You made peace with Darius and kept half an empire; Alexander refused, and took it all' }, hint: 'Gold and peace, and the war is over' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander refused: “So would I, were I Parmenion.” He wrote back that he was now king of Asia, and that Darius should come to him as to his master.',
    },
    {
      id: 'tyre', from: 3, until: 6, if: (q) => q.owns('persia', 'tyre') && q.near('macedon', 'tyre'), title: 'The island city', art: 'siege',
      text: 'Tyre will not let you sacrifice in its temple, and shuts its gates. The city stands on an island half a mile out to sea, with walls 150 feet high, and the Persian fleet uses its harbour.',
      options: [
        { label: 'Build a causeway out to it', fx: { gold: -40, then: (s) => { s.prov.tyre.walls = 1; s.prov.tyre.garrison = 6000; } }, hint: 'Months of labour, but the walls can then be stormed' },
        { label: 'Leave Tyre behind', fx: { sides: { persia: { fleet: 3 } } }, hint: 'Save the time; the Persian fleet keeps its base behind you' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander built a causeway half a mile long, under fire from the walls, and stormed the city after seven months. Some 8,000 Tyrians were killed and 30,000 sold as slaves; the Persian fleet, losing its bases, broke up.',
    },
    {
      id: 'siwa', from: 5, until: 6, if: (q) => q.owns('macedon', 'memphis'), title: 'The oracle in the desert', art: 'expedition',
      text: 'Egypt has welcomed you as a liberator from Persia. Far out in the western desert lies the oasis of Siwa and the oracle of Ammon, whom the Greeks call Zeus. Your priests say the god would greet you as his son.',
      options: [
        { label: 'Cross the desert to Siwa', fx: { will: 6, men: -1500 }, hint: 'A legend for your men to tell, and a hard road' },
        { label: 'Found a city on the coast instead', fx: { gold: 60 }, hint: 'A harbour for trade: Alexandria' },
      ],
      pick: 0, advise: 1,
      history: 'Alexander founded Alexandria, and then crossed the desert to Siwa, where the priest greeted him as son of the god. He never said what he asked the oracle.',
    },
    {
      id: 'night', from: 5, until: 7, if: (q) => !!q.army('darius'), title: 'The night before Gaugamela', art: 'battle',
      text: 'Darius has gathered the whole empire on a flat plain he has cleared for his chariots. His army is many times yours. Parmenion urges you to attack in the dark, when numbers count for less.',
      options: [
        { label: 'Fight by daylight', fx: { morale: 12 }, hint: 'Your men see you will not steal a victory; choose your plan well' },
        { label: 'Attack by night', fx: { chance: 0.5, win: { sides: { persia: { will: -10 } }, log: 'The night attack throws the Persian camp into confusion' }, lose: { morale: -15, log: 'The night attack goes astray in the dark' } }, hint: 'A gamble in the dark' },
      ],
      pick: 0, advise: 0,
      history: '“I will not steal my victory,” Alexander said, and slept soundly. The next day he drew the Persian line to his right, then charged into the gap that opened at its centre, straight at Darius, who fled.',
    },
    {
      id: 'palace', from: 7, until: 8, if: (q) => q.owns('macedon', 'persepolis'), title: 'The palace of Persepolis', art: 'fallen',
      text: 'Persepolis, the treasure-house of the Persian kings, is yours. Some say burn the palace, in revenge for Xerxes’s burning of Athens. Others say a king does not burn his own house.',
      options: [
        { label: 'Burn the palace', fx: { will: 6, sides: { persia: { will: -10 } } }, hint: 'Revenge for Greece, and a sign the old empire is over' },
        { label: 'Keep it as your own', fx: { gold: 120 }, hint: 'The treasure and the goodwill of the Persians' },
      ],
      pick: 0, advise: 1,
      history: 'Alexander’s men looted the city. Months later the palace burned during a feast, on a drunken whim, it was said, or as revenge for Athens. Alexander later regretted it.',
    },
    {
      id: 'dress', from: 8, until: 9, title: 'King of Asia', art: 'crowned',
      text: 'Darius is dead, murdered by his own satrap Bessus. To rule the Persians you could take up Persian dress and court ritual, and make Persian nobles your officers. Your Macedonians would hate it.',
      options: [
        { label: 'Rule as a Persian king', fx: { will: -8, gold: 80, sides: { persia: { will: -15 } } }, hint: 'Persia accepts you, and your own men grumble' },
        { label: 'Stay a Macedonian king', fx: { will: 6, sides: { persia: { will: 5 } } }, hint: 'Your men are glad, and Persia sees a conqueror' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander took up Persian dress and court ritual and promoted Persian nobles. His officers resented it; some plotted, Parmenion was put to death, and Cleitus was killed in a drunken quarrel.',
    },
    {
      id: 'hyphasis', from: 12, if: (q) => INDIA.includes(q.hero()?.at), title: 'The river Hyphasis', art: 'uprising',
      text: 'Your army has marched twenty thousand miles in eight years. Beyond the Hyphasis, they hear, lie the Ganges and kingdoms with thousands of elephants. Your veterans will not go on. Coenus speaks for them.',
      options: [
        { label: 'Turn back', fx: { will: 18 }, hint: 'Your men cheer you; the world’s edge will wait' },
        { label: 'Press on to the Ganges', fx: { will: -30 }, hint: 'Your will against theirs' },
      ],
      pick: 0, advise: 0,
      history: 'Alexander sulked in his tent for three days, then agreed to turn back. His men wept with joy.',
    },
  ],
  events: [
    { id: 'memnon', at: 2, if: (q) => q.living('Memnon of Rhodes'), side: 'persia', fx: { remove: 'memnon', kill: 'Memnon of Rhodes', fleet: 1 }, text: 'Memnon of Rhodes, Persia’s ablest general, dies of an illness while carrying the war to the Aegean', sides: ['persia'] },
    { id: 'darius', at: 2, side: 'persia', fx: { free: ['darius'], aim: { darius: 'issus' } }, text: 'Darius marches out of Babylon with the army of the empire', sides: ['persia'] },
    { id: 'agis', at: 6, if: (q) => q.alive('sparta'), side: 'sparta', fx: { free: ['agis'], rel: ['sparta', 'macedon', 'war'] }, text: 'King Agis III of Sparta rises against Macedon, with Persian gold', sides: ['sparta'] },
    { id: 'babylon', from: 4, if: (q) => q.great() >= 2 && q.near('macedon', 'babylon') && q.owns('persia', 'babylon') && !q.at('persia', 'babylon'), fx: { give: ['babylon', 'macedon'], then: (s) => { s.sides.macedon.gold += 250; s.prov.babylon.looted = true; } }, text: 'The satrap Mazaeus surrenders Babylon, and its people strew the road with flowers', sides: ['macedon', 'persia'] },
    { id: 'susa', from: 4, if: (q) => q.owns('macedon', 'babylon') && q.near('macedon', 'susa') && q.owns('persia', 'susa') && !q.at('persia', 'susa'), fx: { give: ['susa', 'macedon'], then: (s) => { s.sides.macedon.gold += 350; s.prov.susa.looted = true; } }, text: 'Susa opens its gates, and with them the Great King’s treasury', sides: ['macedon', 'persia'] },
    { id: 'bessus', at: 8, if: (q) => !q.owns('persia', 'babylon') && q.alive('persia'), side: 'persia', fx: { remove: 'darius', kill: 'Darius III', leader: 'Bessus, who calls himself King of Kings', free: ['bessus'], will: -10 }, text: 'Darius is murdered by his own satrap Bessus, who calls himself King of Kings', sides: ['persia'] },
    { id: 'parmenion', at: 8, if: (q) => q.living('Parmenion'), side: 'macedon', fx: { kill: 'Parmenion' }, text: 'Parmenion is put to death at Ecbatana, after his son Philotas is condemned for a plot against you', sides: ['macedon'] },
    { id: 'bessusend', at: 9, if: (q) => q.living('Bessus') && !q.living('Darius III'), side: 'persia', fx: { kill: 'Bessus', succeed: { Bessus: ['the Bactrian lords', 2] }, leader: 'the lords of Bactria and Sogdiana' }, text: 'Spitamenes hands Bessus over in chains, and the false king is put to death', sides: ['persia'] },
    { id: 'hephaestion', at: 14, if: (q) => q.living('Hephaestion'), side: 'macedon', fx: { kill: 'Hephaestion' }, text: 'Hephaestion, your dearest friend, dies of a fever at Ecbatana', sides: ['macedon'] },
    { id: 'spitamenes', at: 10, if: (q) => q.owns('macedon', 'maracanda') || q.owns('macedon', 'bactra'), fx: { give: ['maracanda', 'sogdians'], spawn: ['sogdians', 'maracanda', 15000, 'Spitamenes', 4, { id: 'spitamenes' }], rel: ['sogdians', 'macedon', 'war'] }, text: 'Spitamenes leads Sogdiana in revolt and slaughters a Macedonian column', sides: ['sogdians'] },
    { id: 'ambhi', from: 9, if: (q) => q.alive('taxila') && (['kapisa', 'arachosia', 'bactra'].includes(q.hero()?.at) || q.near('macedon', 'taxila')), fx: { rel: [['taxila', 'macedon', 'ally'], ['porus', 'macedon', 'war']], give: ['taxila', 'macedon'], free: ['porus'] }, text: 'King Ambhi of Taxila opens his city to Alexander; King Porus waits across the Hydaspes', sides: ['taxila', 'porus'] },
  ],
};
