// The Gallic Wars, 58–50 BC: Julius Caesar's conquest of Gaul.
const GAUL = ['helvetii', 'aedui', 'sequani', 'arverni', 'bituriges', 'carnutes', 'senones', 'parisii', 'bellovaci', 'remi', 'nervii', 'morini', 'treveri', 'veneti', 'aremorica', 'aquitani', 'alesia', 'santones'];

export default {
  id: 'caesar', n: 6, era: 'The ancient world', age: 'ancient',
  title: 'Caesar in Gaul', years: '58–50 BC',
  you: 'rome',
  hero: { name: 'Julius Caesar', title: 'proconsul of Gaul', look: 'roman' },
  advisor: { name: 'Titus Labienus', title: 'your best legate', look: 'roman' },
  hook: 'Win Gaul, and the glory to rule Rome.',
  art: 'war',
  brief: [
    'Spring 58 BC. You are Gaius Julius Caesar, forty-two years old and deep in debt, governor of the Roman provinces on both sides of the Alps for five years. You have four legions, and you need a war: glory and gold to beat your rivals in Rome.',
    'Beyond the Province lies free Gaul: dozens of proud tribes, often at war with each other, with Germans pressing over the Rhine. The Helvetii are on the move. Divide them, and Gaul is yours. United, they could drive Rome out.',
  ],
  goal: {
    kind: 'custom', provs: GAUL, text: 'Bring Gaul under Rome: break the great revolt, or hold twelve of its eighteen tribes', won: 'Gaul is Roman, from the Pyrenees to the Rhine',
    check: (q, s) => {
      const held = GAUL.filter((p) => s.prov[p].owner === 'rome' || (s.prov[p].owner && s.rel[[s.prov[p].owner, 'rome'].sort().join('|')] === 'ally')).length;
      const broken = q.flag('revolt') && q.ally('gauls', 'rome');
      return { met: broken || held >= 12, progress: Math.max(held / 12, broken ? 1 : 0), text: `${held} of 18 tribes are Rome’s or Rome’s clients${q.flag('revolt') ? (broken ? '; the revolt is broken' : '; Vercingetorix’s revolt still burns') : ''}` };
    },
  },
  lose: { hero: 'Caesar has fallen in Gaul', will: 'The Senate recalls you in disgrace', capital: 'The Gauls have crossed the Alps into Italy' },
  history: {
    won: true, at: 7,
    text: 'Caesar conquered Gaul. In eight years he beat the Helvetii, the Germans of Ariovistus, the Belgae and the Veneti, crossed the Rhine and the sea to Britain, and in 52 BC defeated the great revolt of Vercingetorix at Alesia. Perhaps a million Gauls died and as many were enslaved. In January 49 BC he crossed the Rubicon and started the civil war that made him master of Rome.',
    better: 'Conquer Gaul in less time.',
  },
  view: [42.4, -5.6, 52.4, 12.6],
  reach: 140,
  turns: ['Spring 58 BC', 'Summer 57 BC', 'Summer 56 BC', 'Summer 55 BC', 'Summer 54 BC', 'Spring 53 BC', 'Spring 52 BC', 'Autumn 52 BC', 'Summer 51 BC', 'Winter 50 BC'],
  meanwhile: [
    'The Helvetii set out to migrate across Gaul. Caesar blocks them at Geneva and destroys them at Bibracte. In the autumn he drives the German king Ariovistus back over the Rhine.',
    'The Belgic tribes of the north rise. At the river Sabis the Nervii nearly overwhelm the legions; Caesar seizes a shield and rallies the front line himself.',
    'Caesar’s fleet beats the seafaring Veneti off Brittany, cutting their ships’ rigging with hooks on poles. His officer Crassus conquers Aquitania.',
    'Caesar bridges the Rhine in ten days to frighten the Germans, then crosses to Britain, the first Roman army to land there.',
    'A second, larger expedition reaches the Thames. In the winter Ambiorix of the Eburones wipes out a legion and a half.',
    'Caesar takes revenge on the Eburones and crosses the Rhine again. In the east his ally Crassus is killed by the Parthians at Carrhae.',
    'Gaul rises under Vercingetorix of the Arverni, who burns the land in Caesar’s path. Caesar storms Avaricum but is beaten at Gergovia.',
    'Vercingetorix shuts himself in Alesia. Caesar builds two rings of walls round it, beats the great Gallic relief army, and Vercingetorix surrenders.',
    'The last strongholds fall; at Uxellodunum Caesar has the defenders’ hands cut off. Gaul is Roman.',
    'Recalled by a hostile Senate, Caesar crosses the Rubicon with one legion in January 49 BC: civil war.',
  ],
  sides: {
    rome: { name: 'Caesar’s legions', short: 'Rome', color: '#a3361f', leader: 'Julius Caesar', capital: 'cisalpina', gold: 120, will: 70, quality: 1.4, horse: 0.1, fleet: 0, levy: 10000, income: 30, weariness: 0.6, persona: 'Julius Caesar: quick, bold and merciless, writing his own history as he goes.' },
    aedui: { name: 'The Aedui', color: '#4f7a3a', leader: 'Diviciacus', capital: 'aedui', gold: 60, will: 50, quality: 0.85, horse: 0.25, levy: 4000, ai: 'cautious', submits: true, persona: 'The Aedui, “brothers of the Roman people”, who use Rome against their rivals.' },
    helvetii: { name: 'The Helvetii', color: '#8c6b3f', leader: 'Orgetorix’s people', capital: 'helvetii', gold: 40, will: 60, quality: 0.85, horse: 0.15, levy: 0, ai: 'steady', submits: true, persona: 'The Helvetii, a whole people on the move, looking for new land in the west.' },
    germans: { name: 'Ariovistus’s Germans', short: 'Germans', color: '#5d4a6a', leader: 'King Ariovistus', capital: 'germania', gold: 40, will: 60, quality: 0.95, horse: 0.3, levy: 4000, ai: 'bold', persona: 'Ariovistus, a Suebian king invited into Gaul who now rules it like a conqueror.' },
    belgae: { name: 'The Belgae', color: '#3d6b8c', leader: 'Galba of the Suessiones, and the Nervii', capital: 'bellovaci', gold: 50, will: 60, quality: 0.95, horse: 0.15, levy: 6000, ai: 'bold', submits: true, weariness: 1.5, persona: 'The Belgae of the north, the bravest of the Gauls, the Nervii proudest of all.' },
    veneti: { name: 'The Veneti and Armorica', short: 'Veneti', color: '#2b7d7a', leader: 'the Veneti', capital: 'veneti', gold: 50, will: 60, quality: 0.8, horse: 0.1, fleet: 2, levy: 3000, ai: 'cautious', submits: true, persona: 'The Veneti, masters of the Atlantic coast with their tall oak ships.' },
    aquitani: { name: 'The Aquitani', color: '#9a7a2a', leader: 'the Aquitanian tribes', capital: 'aquitani', gold: 30, will: 50, quality: 0.8, horse: 0.15, levy: 3000, ai: 'cautious', submits: true, persona: 'The tribes of Aquitania, between the Garonne and the Pyrenees.' },
    gauls: { name: 'The Gauls', color: '#c2541f', leader: 'Vercingetorix of the Arverni', capital: 'arverni', gold: 80, will: 70, quality: 0.85, horse: 0.25, levy: 8000, ai: 'cunning', submits: true, persona: 'The free tribes of central Gaul; from 52 BC, Vercingetorix, a young Arvernian noble who unites them and burns the land before the Romans.' },
    britons: { name: 'The Britons', color: '#6a5032', leader: 'Cassivellaunus', capital: 'britain', gold: 30, will: 60, quality: 0.8, horse: 0.25, levy: 3000, ai: 'cautious', submits: true, persona: 'The tribes of Britain beyond the sea, with their war chariots.' },
  },
  provinces: [
    ['cisalpina', 'Mediolanum', 45.46, 9.19, 'rome', 2, 3],
    ['ravenna', 'Ravenna', 44.42, 12.2, 'rome', 1, 2],
    ['narbo', 'Narbo', 43.18, 3.0, 'rome', 1, 3],
    ['tolosa', 'Tolosa', 43.6, 1.44, 'rome', 1, 2],
    ['massalia', 'Massalia', 43.3, 5.37, 'rome', 2, 3],
    ['vienna', 'Vienna', 45.52, 4.87, 'rome', 1, 2],
    ['geneva', 'Genava', 46.2, 6.15, 'rome', 0, 1, { narrows: true }],
    ['helvetii', 'Aventicum', 46.88, 7.04, 'helvetii', 0, 2],
    ['aedui', 'Bibracte', 46.92, 4.04, 'aedui', 2, 3, { terrain: 'hills' }],
    ['sequani', 'Vesontio', 47.24, 6.02, 'gauls', 1, 2],
    ['alesia', 'Alesia', 47.54, 4.5, 'gauls', 3, 1, { terrain: 'hills' }],
    ['arverni', 'Gergovia', 45.71, 3.11, 'gauls', 2, 3, { terrain: 'hills' }],
    ['bituriges', 'Avaricum', 47.08, 2.4, 'gauls', 2, 3],
    ['santones', 'Mediolanum Santonum', 45.75, -0.63, 'gauls', 0, 2],
    ['carnutes', 'Cenabum', 47.9, 1.91, 'gauls', 1, 2],
    ['senones', 'Agedincum', 48.2, 3.28, 'gauls', 0, 2],
    ['parisii', 'Lutetia', 48.86, 2.35, 'gauls', 0, 1],
    ['remi', 'Durocortorum', 49.26, 4.03, 'belgae', 1, 2],
    ['bellovaci', 'Bratuspantium', 49.43, 2.08, 'belgae', 0, 2],
    ['nervii', 'The Sabis', 50.3, 3.79, 'belgae', 0, 1, { terrain: 'forest' }],
    ['morini', 'Gesoriacum', 50.73, 1.61, 'belgae', 0, 1],
    ['treveri', 'Treveri', 49.75, 6.64, 'gauls', 0, 2, { terrain: 'forest' }],
    ['veneti', 'Darioritum', 47.66, -2.76, 'veneti', 1, 2],
    ['aremorica', 'Condate', 48.11, -1.68, 'veneti', 0, 1],
    ['aquitani', 'Burdigala', 44.84, -0.58, 'aquitani', 0, 2],
    ['germania', 'The Rhine', 50.4, 7.6, 'germans', 0, 1, { terrain: 'forest' }],
    ['britain', 'Cantium', 51.28, 1.08, 'britons', 0, 1],
    ['thames', 'The Thames', 51.6, -0.2, 'britons', 0, 2],
  ],
  sea: [['morini', 'britain']],
  cut: [['cisalpina', 'helvetii'], ['cisalpina', 'treveri'], ['cisalpina', 'geneva']],
  straits: [['britain', 'thames']],
  armies: [
    ['rome', 'vienna', 24000, 'Julius Caesar', 5, { hero: true, id: 'caesar' }],
    ['rome', 'narbo', 12000, 'Titus Labienus', 4, { id: 'labienus' }],
    ['helvetii', 'helvetii', 60000, 'the Helvetii', 2, { id: 'helvetii', target: 'santones', temper: 'steady' }],
    ['aedui', 'aedui', 8000, 'Diviciacus', 2, { id: 'diviciacus', stay: true }],
    ['germans', 'sequani', 30000, 'Ariovistus', 3, { id: 'ariovistus', stay: true }],
    ['belgae', 'bellovaci', 40000, 'Galba', 3, { id: 'galba', stay: true }],
    ['belgae', 'nervii', 25000, 'Boduognatus', 4, { id: 'nervii', stay: true, temper: 'rash' }],
    ['veneti', 'veneti', 12000, 'the Veneti', 2, { id: 'venetiArmy', stay: true }],
    ['aquitani', 'aquitani', 10000, 'the Aquitani', 2, { id: 'aquitaniArmy', stay: true }],
    ['gauls', 'arverni', 12000, 'the Arverni', 2, { id: 'arverni', stay: true }],
    ['gauls', 'treveri', 8000, 'Indutiomarus', 2, { id: 'treveriArmy', stay: true }],
    ['britons', 'thames', 10000, 'Cassivellaunus', 3, { id: 'cassivellaunus', stay: true }],
  ],
  wars: [['rome', 'helvetii']],
  allies: [['rome', 'aedui']],
  cards: [
    {
      id: 'helvetii', at: 0, title: 'The Helvetii on the move', art: 'horde',
      text: 'Some 300,000 Helvetii, men, women and children, have burned their villages to migrate to the west of Gaul. They ask to pass through the Roman Province. Your old enemies in Rome would call refusing them a war you had no right to start.',
      options: [
        { label: 'Refuse, and wall them out', fx: { fort: { caesar: 1.4 }, will: 4 }, hint: 'Close the Rhône with a wall nineteen miles long; then follow them' },
        { label: 'Let them pass', fx: { will: -6, sides: { aedui: { will: -10 } } }, hint: 'No war; the Aedui, whose lands they will cross, are furious' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar refused, built a wall along the Rhône, and followed the Helvetii when they went another way. At Bibracte he destroyed them; by his own count only a third survived, and he sent them home.',
    },
    {
      id: 'ariovistus', at: 0, title: 'Ariovistus', art: 'war',
      text: 'The Aedui beg for help: the German king Ariovistus, invited in to fight their rivals, now holds a third of the Sequani’s land and takes hostages from all. Rome named him “friend of the Roman people” only last year.',
      options: [
        { label: 'March against him', fx: { rel: ['rome', 'germans', 'war'], free: ['ariovistus'], sides: { aedui: { will: 10 } } }, hint: 'Drive the Germans out of Gaul' },
        { label: 'Leave a friend of Rome alone', fx: { sides: { aedui: { will: -12 } } }, hint: 'And the Germans keep coming' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar marched. His men, terrified of the Germans, were near mutiny until he said he would go on with the Tenth Legion alone. In September 58 BC he routed Ariovistus, who fled over the Rhine.',
    },
    {
      id: 'bridge', at: 3, title: 'The Rhine', art: 'built',
      text: 'German tribes keep crossing the Rhine into Gaul. You could cross it to show them Rome can reach them too: by boat, as the Ubii offer, or on a bridge your engineers say they can build.',
      options: [
        { label: 'Build a bridge across the Rhine', fx: { gold: -30, will: 8, sides: { germans: { will: -20 } } }, hint: 'A wonder in ten days, and a lesson for the Germans' },
        { label: 'Stay on the Gallic bank', fx: {}, hint: 'Save the effort' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar’s engineers bridged the Rhine in ten days. He spent eighteen days on the far bank burning villages, then crossed back and broke the bridge behind him.',
    },
    {
      id: 'britain', at: 3, title: 'The island beyond the sea', art: 'expedition',
      text: 'Britain lies across the narrow sea: the Britons have sent help to the Gauls, and no Roman has ever been there. An expedition would astonish Rome.',
      options: [
        { label: 'Sail with two legions', fx: { chance: 0.6, win: { will: 12, log: 'The legions land in Britain: Rome votes twenty days of thanksgiving' }, lose: { will: -4, men: -3000, log: 'A storm wrecks the transports; the legions barely get home' } }, hint: 'Glory, if the sea allows' },
        { label: 'Stay in Gaul', fx: {}, hint: 'There is enough to do here' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar landed in Kent in 55 BC under a hail of javelins, after his standard-bearer of the Tenth leapt into the sea first. A storm wrecked many ships; he went home after three weeks. Rome voted twenty days of thanksgiving all the same.',
    },
    {
      id: 'senate', at: 5, title: 'Enemies in Rome', art: 'court',
      text: 'Crassus, your partner in power, has been killed in Parthia. Your enemies in the Senate want you recalled and tried. Your daughter Julia, Pompey’s wife, is dead. Gold from Gaul could buy you friends.',
      options: [
        { label: 'Send gold to Rome', fx: { gold: -80, will: 10 }, hint: 'Buy magistrates and the mob' },
        { label: 'Trust your name and your victories', fx: { will: -6 }, hint: 'Keep the gold for the legions' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar spent the plunder of Gaul freely in Rome: on buildings, games and bribes. It was not enough to stop the Senate and Pompey moving against him.',
    },
    {
      id: 'gergovia', at: 6, if: (q) => q.alive('gauls') && q.owns('gauls', 'arverni'), title: 'The heights of Gergovia', art: 'siege',
      text: 'Vercingetorix holds Gergovia, a town on a high plateau, with his army camped on the slopes. Your men are eager to storm it. Your siege is going slowly, and the Aedui behind you are wavering.',
      options: [
        { label: 'Storm the heights', fx: { chance: 0.35, win: { give: ['arverni', 'rome'], sides: { gauls: { will: -15 } }, log: 'The legions storm Gergovia' }, lose: { men: -5000, will: -8, log: 'The assault on Gergovia is thrown back: nearly 700 Romans, 46 of them centurions, die on the slopes' } }, hint: 'A quick end, if it works' },
        { label: 'Withdraw and join Labienus', fx: { will: -4 }, hint: 'Lose face, keep your army' },
      ],
      pick: 0, advise: 1,
      history: 'Caesar’s men went too far up the hill against orders and were thrown back with heavy losses: his only real defeat in Gaul. He withdrew north and joined Labienus.',
    },
    {
      id: 'alesia', from: 7, if: (q) => q.at('rome', 'alesia') || q.near('rome', 'alesia'), title: 'Two rings of walls', art: 'siege',
      text: 'Vercingetorix and 80,000 men are shut up in the hill town of Alesia. A great Gallic army is gathering to relieve them. You could build a wall round the town to starve it, and a second, facing outwards, to hold off the relief.',
      options: [
        { label: 'Build both walls', fx: { fort: { caesar: 1.9 }, gold: -40 }, hint: 'Ten miles of walls, towers and traps; then hold them from both sides' },
        { label: 'Storm the town now', fx: { morale: 8 }, hint: 'Before the relief arrives' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar built a ring of walls eleven miles round Alesia and another fourteen miles round that, with ditches, stakes and pits. The relief army broke on the outer wall; Vercingetorix rode out and laid down his arms at Caesar’s feet.',
    },
    {
      id: 'rubicon', at: 9, title: 'The Rubicon', art: 'crowned',
      text: 'The Senate orders you to give up your army and come to Rome as a private man, where your enemies will put you on trial. You stand at the Rubicon, the border of Italy, with one legion.',
      options: [
        { label: '“The die is cast”: cross', fx: { will: 12 }, hint: 'Civil war' },
        { label: 'Give up your army and obey', fx: { will: -25 }, hint: 'And trust your enemies' },
      ],
      pick: 0, advise: 0,
      history: 'Caesar crossed the Rubicon in January 49 BC, saying “the die is cast”. Four years of civil war later he was master of Rome, until the Ides of March, 44 BC.',
    },
  ],
  events: [
    { id: 'belgae', at: 1, fx: { rel: [['belgae', 'rome', 'war']], free: ['galba', 'nervii'], give: ['remi', 'rome'] }, text: 'The Belgae rise against Rome; the Remi go over to Caesar', sides: ['belgae', 'rome'] },
    { id: 'west', at: 2, fx: { rel: [['veneti', 'rome', 'war'], ['aquitani', 'rome', 'war']], free: ['venetiArmy', 'aquitaniArmy'], fleet: 1 }, text: 'The Veneti seize Roman envoys, and the Atlantic coast rises; Caesar builds a fleet on the Loire', sides: ['veneti', 'aquitani', 'rome'] },
    { id: 'britons', at: 3, fx: { rel: [['britons', 'rome', 'war']] }, text: 'The Britons have sent help to the Gauls: Rome looks across the sea', sides: ['britons'] },
    {
      id: 'ambiorix', at: 4, if: (q) => q.alive('gauls'), side: 'gauls', sides: ['gauls', 'rome'],
      text: 'Ambiorix of the Eburones lures a legion and a half out of its winter camp and wipes it out',
      fx: { rel: [['gauls', 'rome', 'war']], free: ['treveriArmy'], spawn: ['gauls', 'treveri', 12000, 'Ambiorix', 4, { id: 'ambiorix', temper: 'cunning' }], then: (s) => { const r = Object.values(s.armies).filter((a) => a.side === 'rome' && !a.hero).sort((a, b) => a.men - b.men)[0]; if (r) r.men = Math.max(1000, r.men - 8000); } },
    },
    {
      id: 'vercingetorix', at: 6, side: 'gauls', sides: ['gauls', 'aedui', 'rome'],
      text: 'All Gaul rises under Vercingetorix of the Arverni; even the Aedui turn against Rome',
      fx: { flag: 'revolt', rel: [['gauls', 'rome', 'war'], ['aedui', 'rome', 'war'], ['aedui', 'gauls', 'ally']], free: ['arverni', 'diviciacus'], spawn: ['gauls', 'arverni', 50000, 'Vercingetorix', 5, { id: 'vercingetorix', temper: 'cunning' }], will: 25 },
    },
    { id: 'shut', at: 7, if: (q) => !!q.army('vercingetorix'), side: 'gauls', fx: { then: (s) => { const v = s.armies.vercingetorix; v.at = 'alesia'; v.from = 'alesia'; v.stay = true; s.prov.alesia.owner = 'gauls'; } }, text: 'Vercingetorix shuts himself and his army up in the hill town of Alesia', sides: ['gauls'] },
    { id: 'surrender', from: 7, if: (q) => q.flag('revolt') && q.war('gauls', 'rome') && (q.owns('rome', 'alesia') || !q.army('vercingetorix')), side: 'gauls', fx: { will: -60, remove: 'vercingetorix' }, text: 'Vercingetorix rides out of Alesia in his finest armour and lays down his arms at Caesar’s feet; the great revolt is over', sides: ['gauls', 'rome'] },
    { id: 'relief', at: 7, if: (q) => !!q.army('vercingetorix'), side: 'gauls', fx: { spawn: ['gauls', 'sequani', 60000, 'the relief army', 3, { id: 'relief', target: 'alesia', temper: 'bold' }] }, text: 'A great relief army gathers from every tribe of Gaul to save Vercingetorix', sides: ['gauls'] },
  ],
};
