// The Second Punic War, 218–202 BC: Hannibal carries the war to Italy to break Rome's will.
const ITALY = ['taurini', 'insubres', 'placentia', 'boii', 'genua', 'ariminum', 'arretium', 'trasimene', 'picenum', 'rome', 'capua', 'samnium', 'cannae', 'tarentum', 'lucania', 'bruttium', 'rhegium'];
const SPAIN = ['newcarthage', 'gades', 'castulo', 'saguntum', 'toletum'];

export default {
  id: 'hannibal', n: 4, era: 'The ancient world', age: 'ancient',
  title: 'Hannibal at the Gates', years: '218–202 BC',
  you: 'carthage',
  hero: { name: 'Hannibal Barca', title: 'General of Carthage', born: -247, look: 'punic', female: false },
  advisor: { name: 'Maharbal', title: 'commander of your horse', look: 'punic' },
  hook: 'Cross the Alps with your elephants and bring Rome to its knees.',
  brief: [
    'Spring 218 BC. Twenty-three years ago Rome beat Carthage in the first war between them and took Sicily, then Sardinia. Your father Hamilcar rebuilt Carthage’s power in Spain. You have just taken Saguntum, Rome’s friend, and Rome has declared war.',
    'Rome rules the sea, so it expects to fight you in Spain and in Africa. You mean to carry the war to Italy, where Rome’s allies might desert it. Rome can raise more men than anyone: you cannot kill them all. You must break its will.',
  ],
  goal: { kind: 'peace', foe: 'rome', text: 'Force Rome to make peace', won: 'Rome sues for peace: Carthage is mistress of the western sea' },
  lose: { hero: 'Hannibal has fallen, and with him the war', capital: 'Carthage has fallen to Rome', will: 'Carthage has lost heart: the council recalls you and makes peace' },
  history: {
    won: false, at: 17,
    text: 'Rome never broke. After Cannae it refused to negotiate, raised new legions and fought Hannibal’s allies instead of Hannibal himself. Scipio took Spain, landed in Africa and defeated Hannibal at Zama in 202 BC. In the peace of 201 BC Carthage gave up Spain, its fleet and the right to make war without Rome’s leave.',
    better: 'Make Rome sue for peace, which no enemy ever forced it to do.',
  },
  view: [34.6, -7.5, 46.6, 18.6],
  turns: ['Spring 218 BC', 'Autumn 218 BC', 'Spring 217 BC', 'Autumn 217 BC', 'Summer 216 BC', 'Spring 215 BC', 'Spring 214 BC', 'Spring 213 BC', 'Spring 212 BC', 'Spring 211 BC', 'Spring 210 BC', 'Spring 209 BC', 'Spring 208 BC', 'Spring 207 BC', 'Spring 205 BC', 'Spring 204 BC', 'Autumn 203 BC', 'Autumn 202 BC'],
  meanwhile: [
    'Hannibal leaves New Carthage with a great army and 37 elephants. Rome declares war over the fall of Saguntum.',
    'Hannibal crosses the Alps in October with heavy losses. In December he beats the consul Sempronius at the river Trebia.',
    'In June, Hannibal ambushes the consul Flaminius in the morning mist by Lake Trasimene. Some 15,000 Romans die, Flaminius among them.',
    'Rome names Fabius Maximus dictator. He shadows Hannibal and refuses battle, and the Romans mock him as “the Delayer”.',
    'On 2 August, at Cannae, Hannibal surrounds and destroys the largest army Rome has ever raised.',
    'Capua and much of southern Italy go over to Hannibal. Philip V of Macedon makes an alliance with him.',
    'Syracuse turns against Rome. Rome refuses to talk of peace and raises new legions, even from slaves.',
    'The consul Marcellus besieges Syracuse. The machines of Archimedes keep the Roman fleet at bay.',
    'Tarentum opens its gates to Hannibal. Syracuse falls to Marcellus and Archimedes is killed. Rome besieges Capua.',
    'Hannibal marches to the gates of Rome to draw the legions away from Capua, but Rome holds firm and Capua falls. In Spain both Scipio brothers are killed.',
    'The young Publius Cornelius Scipio, about 25 years old, is sent to Spain to avenge his father and his uncle.',
    'Scipio storms New Carthage in a single day. Rome retakes Tarentum.',
    'Scipio beats Hasdrubal at Baecula, but Hasdrubal slips away toward the Alps with his army.',
    'Hasdrubal reaches Italy, but his letters to Hannibal are captured. He is beaten and killed at the Metaurus, and his head is thrown into Hannibal’s camp.',
    'Scipio, victorious in Spain, is elected consul and prepares to invade Africa from Sicily. Hannibal holds out in Bruttium.',
    'Scipio lands near Utica. The Numidian prince Masinissa joins him.',
    'Scipio wins at the Great Plains. Carthage recalls Hannibal from Italy after fifteen years.',
    'At Zama, Scipio and Masinissa defeat Hannibal. Carthage makes peace the next year.',
  ],
  sides: {
    carthage: { name: 'Carthage', color: '#6b2d7b', leader: 'Hannibal Barca', capital: 'carthage', gold: 160, will: 70, weariness: 0.5, quality: 1.1, horse: 0.25, fleet: 0, levy: 12000, persona: 'Hannibal Barca, sworn as a boy to be Rome’s enemy.' },
    rome: { name: 'Rome', color: '#a3361f', leader: 'the Senate and its consuls', capital: 'rome', gold: 220, will: 90, quality: 1.0, horse: 0.1, fleet: 3, levy: 22000, income: 20, weariness: 0.5, ai: 'bold', persona: 'The Roman Senate: proud and stubborn. It never asks for peace after a defeat; it raises new legions instead. Its consuls change every year and want glory.' },
    gauls: { name: 'The Gauls of the Po', short: 'Gauls', color: '#2b7d7a', leader: 'the chiefs of the Insubres and the Boii', capital: 'insubres', gold: 40, will: 60, quality: 0.85, horse: 0.25, levy: 5000, ai: 'rash', persona: 'Celtic chiefs: brave, quarrelsome, eager for plunder, quick to lose heart when the war goes badly.' },
    syracuse: { name: 'Syracuse', color: '#b3852c', leader: 'Hiero II', capital: 'syracuse', gold: 80, will: 55, quality: 0.95, horse: 0.15, fleet: 1, levy: 4000, ai: 'cautious', persona: 'The Greek city of Syracuse: rich and proud of its walls; old King Hiero is Rome’s loyal friend.' },
    numidia: { name: 'Numidia', color: '#8c6b3f', leader: 'Syphax', capital: 'numidia', gold: 50, will: 60, quality: 0.9, horse: 0.6, levy: 5000, ai: 'cunning', persona: 'Numidian princes: the finest horsemen of Africa, who side with whoever is winning.' },
  },
  provinces: [
    // Spain
    ['newcarthage', 'New Carthage', 37.6, -0.98, 'carthage', 2, 3],
    ['gades', 'Gades', 36.53, -6.29, 'carthage', 1, 2],
    ['castulo', 'Castulo', 38.03, -3.63, 'carthage', 0, 3],
    ['saguntum', 'Saguntum', 39.68, -0.27, 'carthage', 1, 2],
    ['toletum', 'Toletum', 39.86, -4.02, 'carthage', 0, 1],
    ['numantia', 'Numantia', 41.81, -2.44, null, 1, 1],
    ['ilerda', 'Ilerda', 41.62, 0.62, null, 0, 1],
    ['tarraco', 'Tarraco', 41.12, 1.25, null, 1, 2],
    ['emporiae', 'Emporiae', 42.13, 3.12, 'rome', 1, 1],
    // Gaul and the Alps
    ['narbo', 'Narbo', 43.18, 3.0, null, 0, 1],
    ['massalia', 'Massalia', 43.3, 5.37, 'rome', 2, 3],
    ['rhone', 'The Rhône', 44.14, 4.81, null, 0, 1],
    ['alps', 'The Alps', 45.2, 6.75, null, 0, 0, { terrain: 'mountains', narrows: true }],
    ['taurini', 'Taurasia', 45.07, 7.69, null, 1, 1],
    ['insubres', 'Mediolanum', 45.46, 9.19, 'gauls', 0, 2],
    ['placentia', 'Placentia', 45.05, 9.69, 'rome', 1, 1],
    ['boii', 'Felsina', 44.49, 11.34, 'gauls', 0, 2],
    ['genua', 'Genua', 44.41, 8.93, null, 0, 1],
    // Italy
    ['ariminum', 'Ariminum', 44.06, 12.57, 'rome', 1, 1],
    ['arretium', 'Arretium', 43.46, 11.88, 'rome', 1, 2],
    ['trasimene', 'Lake Trasimene', 43.13, 12.1, 'rome', 0, 1, { lake: true, terrain: 'hills' }],
    ['picenum', 'Asculum', 42.85, 13.58, 'rome', 0, 1],
    ['rome', 'Rome', 41.89, 12.49, 'rome', 3, 6],
    ['capua', 'Capua', 41.08, 14.25, 'rome', 2, 4],
    ['samnium', 'Beneventum', 41.13, 14.78, 'rome', 1, 1],
    ['cannae', 'Cannae', 41.3, 16.13, 'rome', 0, 2, { terrain: 'plains' }],
    ['tarentum', 'Tarentum', 40.47, 17.24, 'rome', 2, 3],
    ['lucania', 'Grumentum', 40.28, 15.89, 'rome', 0, 1],
    ['bruttium', 'Croton', 39.08, 17.12, 'rome', 1, 1],
    ['rhegium', 'Rhegium', 38.11, 15.65, 'rome', 1, 2],
    // the islands
    ['messana', 'Messana', 38.19, 15.55, 'rome', 1, 2],
    ['panormus', 'Panormus', 38.12, 13.36, 'rome', 1, 2],
    ['lilybaeum', 'Lilybaeum', 37.8, 12.44, 'rome', 2, 2],
    ['syracuse', 'Syracuse', 37.08, 15.29, 'syracuse', 3, 4],
    ['sardinia', 'Carales', 39.22, 9.12, 'rome', 1, 2],
    // Africa
    ['carthage', 'Carthage', 36.85, 10.32, 'carthage', 3, 6],
    ['utica', 'Utica', 37.06, 10.06, 'carthage', 1, 2],
    ['hadrumetum', 'Hadrumetum', 35.83, 10.64, 'carthage', 1, 2],
    ['zama', 'Zama', 36.3, 9.45, 'carthage', 0, 1],
    ['numidia', 'Cirta', 36.37, 6.61, 'numidia', 1, 2],
  ],
  sea: [['lilybaeum', 'carthage'], ['lilybaeum', 'utica'], ['sardinia', 'carthage'], ['rome', 'sardinia'], ['newcarthage', 'carthage'], ['bruttium', 'hadrumetum'], ['syracuse', 'carthage']],
  straits: [['rhegium', 'messana']],
  armies: [
    ['carthage', 'newcarthage', 60000, 'Hannibal Barca', 5, { hero: true, id: 'hannibal' }],
    ['carthage', 'castulo', 15000, 'Hasdrubal Barca', 4, { id: 'hasdrubal' }],
    ['carthage', 'carthage', 16000, 'Hanno', 2, { id: 'hanno' }],
    ['rome', 'massalia', 22000, 'Publius Scipio', 3, { id: 'pscipio' }],
    ['rome', 'lilybaeum', 26000, 'Sempronius Longus', 2, { id: 'sempronius', temper: 'rash', stay: true }],
    ['rome', 'placentia', 12000, 'Manlius', 2, { id: 'manlius' }],
    ['rome', 'rome', 20000, 'Flaminius', 2, { id: 'flaminius', temper: 'rash' }],
    ['gauls', 'insubres', 12000, 'Gallic chiefs', 2, { id: 'gauls' }],
    ['syracuse', 'syracuse', 8000, 'Hiero II', 3, { id: 'hiero', stay: true }],
    ['numidia', 'numidia', 8000, 'Syphax', 3, { id: 'syphax', stay: true }],
  ],
  wars: [['carthage', 'rome'], ['gauls', 'rome']],
  allies: [['carthage', 'numidia'], ['rome', 'syracuse']],
  cards: [
    {
      id: 'road', at: 0, title: 'The road to Italy', art: 'expedition',
      text: 'Rome’s fleets rule the sea, so Rome expects to fight you in Spain and in Africa. Your scouts know a way no army has taken: over the Pyrenees, across Gaul and the Rhône, and through the Alps before the snows close them. The Gauls of the Po, who hate Rome, wait on the other side.',
      options: [
        { label: 'Over the Alps to Italy', fx: { move: ['hannibal', 'taurini'], men: -0.45, flag: 'alps' }, hint: 'Lose nearly half your men to cold, rockfalls and mountain tribes, and appear where Rome least expects you' },
        { label: 'Fight Rome in Spain', fx: { flag: 'spain' }, hint: 'Keep your army whole and let Rome come to you' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal chose the Alps. He left Spain with perhaps 90,000 men and reached Italy in the autumn of 218 BC with about 26,000. The crossing became a legend, and it took Rome completely by surprise.',
    },
    {
      id: 'gauls', at: 1, if: (q) => q.flag('alps') || ITALY.includes(q.hero()?.at),
      title: 'The Gauls of the Po', art: 'horde',
      text: 'The Insubres and the Boii have risen against Rome’s new colonies on the Po. Their chiefs come to your camp: they will fight for you, if you will lead them against Rome.',
      options: [
        { label: 'Welcome them as allies', fx: { rel: ['carthage', 'gauls', 'ally'], men: 9000, sides: { rome: { will: -3 } } }, hint: '9,000 warriors join you, and the Gauls join your war' },
        { label: 'Keep your army Punic', fx: { morale: 5 }, hint: 'Trust only your veterans' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal welcomed them. Gauls made up about a third of his army at Cannae, and many died in the front line, where he placed them.',
    },
    {
      id: 'fabius', from: 2, until: 4, if: (q) => q.flag('fabius'),
      title: 'The Delayer', art: 'siege',
      text: 'Rome has named Quintus Fabius Maximus dictator. He will not fight: he shadows you along the hills, picks off your foragers and waits for you to starve. The Romans call him a coward. Your scouts report that his own estate lies on your road.',
      options: [
        { label: 'Burn the land, but spare his farm', fx: { sides: { rome: { will: -5, ai: 'bold' } } }, hint: 'Make Rome suspect its own dictator, and bring an impatient consul against you' },
        { label: 'Burn everything, his farm too', fx: { gold: 30, sides: { rome: { will: -2 } } }, hint: 'Plunder pays, and Fabius keeps his good name' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal burned everything around Fabius’s estate and left it untouched, so that Rome would suspect its dictator of a secret deal. It worked: Rome lost patience with Fabius and the next year sent the impatient consul Varro against Hannibal.',
    },
    {
      id: 'maharbal', from: 4, until: 6, if: (q) => q.great() >= 2 && q.owns('rome', 'capua'),
      title: 'March on Rome?', art: 'battle',
      text: 'Your cavalry commander Maharbal begs you to march on Rome at once: “In five days you will dine on the Capitol!” But Rome has strong walls and you have no siege engines. In Capua, Italy’s second city, men are whispering about leaving Rome.',
      options: [
        { label: 'March on Rome', fx: { morale: 10, sides: { rome: { will: -4 } } }, hint: 'Shake Rome while it is reeling; then you must take its walls' },
        { label: 'Win over Capua and the south', fx: { give: ['capua', 'carthage'], gold: 40, sides: { rome: { will: -6 } } }, hint: 'Capua opens its gates; you gain a base, gold and allies' },
      ],
      pick: 1, advise: 1,
      history: 'Hannibal did not march on Rome. “You know how to win a victory, Hannibal,” Maharbal told him, “but not how to use one.” Instead he won over Capua and much of the south. Historians still argue over whether Rome could have been taken.',
    },
    {
      id: 'philip', at: 5, title: 'Philip V of Macedon', art: 'charter',
      text: 'Envoys from Philip V of Macedon have slipped past the Roman fleet. Philip offers an alliance: he will make war on Rome’s friends across the Adriatic.',
      options: [
        { label: 'Make the alliance', fx: { flag: 'philip', sides: { rome: { will: -3, gold: -60 } } }, hint: 'Rome must send ships and money east' },
        { label: 'Decline', fx: {}, hint: 'Philip is a fickle friend' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal and Philip swore an alliance in 215 BC. Rome kept Philip busy in Greece with a small force and Greek allies, and no Macedonian soldier ever reached Italy.',
    },
    {
      id: 'syracuse', at: 6, if: (q) => q.alive('syracuse') && q.ally('syracuse', 'rome'),
      title: 'Syracuse wavers', art: 'court',
      text: 'Old King Hiero of Syracuse, Rome’s loyal friend, is dead. His young grandson Hieronymus listens to envoys from Carthage. Syracuse has the strongest walls in the West, and a fleet.',
      options: [
        { label: 'Send gold and envoys', fx: { gold: -50, rel: [['syracuse', 'carthage', 'ally'], ['syracuse', 'rome', 'war']], sides: { rome: { will: -4 } } }, hint: 'Syracuse joins your war, and Rome must send an army against it' },
        { label: 'Leave Sicily to Rome', fx: {}, hint: 'Save your gold' },
      ],
      pick: 0, advise: 0,
      history: 'Syracuse went over to Carthage in 214 BC. Marcellus besieged it for two years; the machines of the mathematician Archimedes held off his fleet, but the city fell in 212 BC and Archimedes was killed.',
    },
    {
      id: 'tarentum', from: 7, until: 9, if: (q) => q.owns('rome', 'tarentum') && ['lucania', 'cannae', 'bruttium', 'samnium', 'tarentum'].includes(q.hero()?.at),
      title: 'The gates of Tarentum', art: 'turncoat',
      text: 'Young Tarentines, angry with Rome for executing their hostages, offer to open the city gates to you at night.',
      options: [
        { label: 'Go in by night', fx: { give: ['tarentum', 'carthage'], sides: { rome: { will: -3 } } }, hint: 'Take Italy’s finest harbour without a siege' },
        { label: 'Refuse: it may be a trap', fx: {}, hint: 'Stay safe' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal entered Tarentum by night in 212 BC, but the Roman garrison held out in the citadel, and Rome took the city back three years later.',
    },
    {
      id: 'brother', from: 11, until: 13, if: (q) => !!q.army('hasdrubal') && SPAIN.some((p) => q.owns('carthage', p)),
      title: 'Your brother’s army', art: 'expedition',
      text: 'Your brother Hasdrubal can leave Spain with his army and cross the Alps as you did. Two Barcid armies in Italy could finish Rome. But Spain would be left open to Scipio, and Hasdrubal’s riders must reach you through Roman land to say where to meet.',
      options: [
        { label: 'Bring him over the Alps', fx: { remove: 'hasdrubal', spawn: ['carthage', 'boii', 30000, 'Hasdrubal Barca', 4, { id: 'hasdrubal2' }], flag: 'brother' }, hint: 'Hasdrubal appears in the Po valley with 30,000 men; Rome will try to catch him alone' },
        { label: 'Keep him in Spain', fx: {}, hint: 'Spain and its silver stay defended' },
      ],
      pick: 0, advise: 0,
      history: 'Hasdrubal crossed the Alps in 207 BC, but the Romans captured his letter to Hannibal. The consul Nero slipped away from Hannibal, joined his colleague and destroyed Hasdrubal’s army at the Metaurus. Hasdrubal fell, and his head was thrown into Hannibal’s camp.',
    },
    {
      id: 'recall', from: 15, if: (q) => q.flag('scipio') && ITALY.includes(q.hero()?.at),
      title: 'Carthage calls you home', art: 'siege',
      text: 'Scipio is burning the farms around Carthage, and the council has sued for a truce. They order you home to save the city.',
      options: [
        { label: 'Sail for Africa', fx: { move: ['hannibal', 'hadrumetum'], men: -0.25 }, hint: 'Defend Carthage, and leave Italy for ever' },
        { label: 'Stay in Italy', fx: { will: -20 }, hint: 'Disobey the council and keep the war in Italy' },
      ],
      pick: 0, advise: 0,
      history: 'Hannibal obeyed. In 203 BC he sailed from Croton after fifteen years in Italy, and landed near Hadrumetum.',
    },
  ],
  events: [
    { id: 'sempronius', at: 1, if: (q) => q.flag('alps'), side: 'rome', fx: { move: ['sempronius', 'ariminum'], free: ['sempronius'] }, text: 'Rome calls Sempronius back from Sicily: his army marches the length of Italy to meet you', sides: ['rome'] },
    { id: 'africa', at: 1, if: (q) => !q.flag('alps'), side: 'rome', fx: { free: ['sempronius'], aim: { sempronius: 'carthage' } }, text: 'Sempronius sails from Sicily to strike at Carthage itself', sides: ['rome'] },
    { id: 'fabius', from: 2, until: 3, if: (q) => q.won() >= 1 && q.alive('rome'), side: 'rome', fx: { ai: 'delaying', flag: 'fabius' }, text: 'Rome names Fabius Maximus dictator: he will shadow you and refuse battle', sides: ['rome'] },
    {
      id: 'varro', at: 4, if: (q) => q.will('rome') > 30, side: 'rome', sides: ['rome'],
      text: 'Rome raises the greatest army in its history, eight legions and as many allies, under the consuls Varro and Paullus',
      fx: { ai: 'bold', then: (s, q, emit, { spawn, C }) => {
        const h = q.hero(), near = h ? [h.at, ...q.neighbors(h.at)].flatMap((p) => [p, ...q.neighbors(p)]).find((p) => q.owns('rome', p) && !q.at('carthage', p)) : null;
        spawn('rome', near ?? 'rome', 75000, 'Varro', 2, { id: 'varro', temper: 'rash' });
      } },
    },
    { id: 'resolve', from: 4, if: (q) => q.great() >= 2 && q.alive('rome'), side: 'rome', fx: { will: 12, ai: 'delaying' }, text: 'Rome refuses to despair: the Senate forbids public mourning, will not ransom its prisoners, arms 8,000 slaves, and will never again meet Hannibal in open battle', sides: ['rome'] },
    { id: 'marcellus', from: 7, if: (q) => q.war('syracuse', 'rome') && q.alive('rome'), side: 'rome', fx: { spawn: ['rome', 'messana', 28000, 'Marcellus', 4, { id: 'marcellus', target: 'syracuse' }] }, text: 'Marcellus, “the Sword of Rome”, crosses to Sicily to besiege Syracuse', sides: ['rome'] },
    {
      id: 'scipio', at: 10, if: (q) => q.alive('rome') && q.will('rome') > 25 && SPAIN.some((p) => q.owns('carthage', p)), side: 'rome', sides: ['rome'],
      text: 'Rome sends the young Publius Cornelius Scipio to Spain to avenge his father and his uncle',
      fx: { give: ['tarraco', 'rome'], spawn: ['rome', 'tarraco', 28000, 'Scipio', 5, { id: 'scipio', target: 'newcarthage', temper: 'bold' }] },
    },
    {
      id: 'nero', at: 13, if: (q) => q.flag('brother') && !!q.army('hasdrubal2') && q.alive('rome'), side: 'rome', sides: ['rome'],
      text: 'The consul Nero slips away from Hannibal with his best men to catch Hasdrubal before the brothers meet',
      fx: { then: (s, q, emit, { spawn }) => {
        const at = q.army('hasdrubal2').at, near = q.neighbors(at).find((p) => q.owns('rome', p)) ?? 'ariminum';
        spawn('rome', near, 32000, 'Claudius Nero', 4, { id: 'nero', target: at, temper: 'bold' });
      } },
    },
    {
      id: 'africanus', at: 15, if: (q) => q.alive('rome') && q.will('rome') > 25 && q.owns('rome', 'lilybaeum') && !q.owns('rome', 'carthage'), side: 'rome', sides: ['rome', 'numidia'],
      text: 'Scipio lands near Utica with 30,000 men, and the Numidian prince Masinissa joins him',
      fx: { flag: 'scipio', spawn: ['rome', 'utica', 30000, 'Scipio Africanus', 5, { id: 'africanus', target: 'carthage', temper: 'bold' }], rel: [['numidia', 'carthage', 'war'], ['numidia', 'rome', 'ally']], sides: { numidia: { ai: 'bold' } }, free: ['syphax'] },
    },
  ],
};
