// The Maccabean revolt, 167–160 BC: Judah Maccabee against the Seleucid Empire.
export default {
  id: 'maccabees', n: 5, era: 'The ancient world', age: 'ancient',
  title: 'The Maccabees', years: '167–160 BC',
  you: 'judeans',
  hero: { name: 'Judah Maccabee', title: 'leader of the Judean revolt', look: 'nabataean' },
  advisor: { name: 'Simon', title: 'your elder brother', look: 'nabataean' },
  hook: 'A few thousand men in the hills against an empire’s phalanx and its elephants.',
  art: 'uprising',
  brief: [
    'Autumn 167 BC. King Antiochus IV of the Seleucid Empire has forbidden the Jews of Judea to live by their own law, and set up an altar to Zeus in the Temple of Jerusalem. At Modein, the old priest Mattathias has killed a royal officer and fled to the hills with his five sons.',
    'You are Judah, his son, called Maccabee, “the Hammer”. You have a few thousand men with little armour. The king has a professional army, cavalry and war elephants. Fight where the hills and the passes are on your side.',
  ],
  goal: {
    kind: 'custom', provs: ['jerusalem'], text: 'Take back Jerusalem and force the king to let Judea live by its own law', won: 'The king gives way: Judea may live by its own law again',
    check: (q, s) => {
      const jer = s.prov.jerusalem.owner === 'judeans', will = s.sides.seleucids.will;
      return { met: jer && will <= 30, progress: (jer ? 0.5 : 0) + Math.min(0.5, (100 - will) / 140), text: `Jerusalem is ${jer ? 'yours' : 'in the king’s hands'}; the king’s will to fight: ${Math.round(will)} (he gives way below 30)` };
    },
  },
  lose: { hero: 'Judah has fallen, and the revolt is crushed', will: 'The revolt loses heart and scatters into the desert' },
  loseCapital: false,
  history: {
    won: true, at: 5,
    text: 'The revolt won its freedom of faith. Judah retook Jerusalem and rededicated the Temple in 164 BC, and in 162 BC the regent Lysias, called home by trouble in Antioch, let the Jews live by their own law. Judah fell fighting at Elasa in 160 BC, but his brothers fought on, and Judea became independent in 142 BC.',
    better: 'Win the king’s consent sooner, and live.',
  },
  view: [30.95, 33.95, 33.65, 36.6],
  reach: 45,
  turns: ['Autumn 167 BC', 'Spring 166 BC', 'Summer 165 BC', 'Autumn 164 BC', 'Spring 163 BC', 'Spring 162 BC', 'Spring 161 BC', 'Spring 160 BC'],
  meanwhile: [
    'King Antiochus IV has banned Jewish law and set up an altar to Zeus in the Temple. At Modein the old priest Mattathias kills a royal officer and flees to the hills with his five sons.',
    'Judah, called Maccabee, takes command after his father’s death. He destroys the column of Apollonius, taking his sword, and routs Seron at the pass of Beth Horon.',
    'At Emmaus Judah slips away from Gorgias’s night raid, burns his camp and scatters the royal army.',
    'Judah beats the regent Lysias at Beth Zur, retakes Jerusalem except its citadel, and rededicates the Temple; the festival of Hanukkah remembers it. Antiochus IV dies on campaign in Persia.',
    'Judah and his brother Simon bring the Jews of Galilee and Gilead to safety in Judea.',
    'At Beth Zechariah the royal army’s war elephants win the day, and Judah’s brother Eleazar dies under one. But trouble at home makes Lysias grant the Jews the right to live by their own law.',
    'At Adasa Judah defeats and kills the general Nicanor. He sends envoys to Rome, which signs a treaty of friendship.',
    'Bacchides returns with 20,000 men. Most of Judah’s army melts away; at Elasa he fights on with 800 men and dies. His brothers carry on the struggle.',
  ],
  sides: {
    judeans: { name: 'The Maccabees', short: 'Judeans', color: '#2e5e8c', leader: 'Judah Maccabee', capital: 'gophna', gold: 40, will: 72, quality: 1.15, horse: 0.02, levy: 2500, income: 6, raiseCost: 6, weariness: 0.4, persona: 'Judah Maccabee and his brothers: devout, fierce, and masters of the hills.' },
    seleucids: { name: 'The Seleucid Empire', short: 'Seleucids', color: '#7a4b8c', leader: 'King Antiochus IV Epiphanes, and the regent Lysias', capital: 'damascus', gold: 260, will: 75, quality: 1.1, horse: 0.15, levy: 3000, income: 10, ai: 'bold', weariness: 1.5, persona: 'The Seleucid court at Antioch: proud of its phalanx and elephants, at war in the east and troubled by rivals at home; it wants Judea quiet, not a long war.' },
    idumea: { name: 'Idumea', color: '#8c6b3f', leader: 'the Idumean chiefs', capital: 'hebron', gold: 20, will: 40, quality: 0.9, horse: 0.1, levy: 1500, ai: 'cautious', persona: 'The Idumeans to the south, old rivals of Judea, friendly to the king.' },
  },
  provinces: [
    ['modein', 'Modein', 31.93, 34.97, 'judeans', 0, 1, { terrain: 'hills' }],
    ['gophna', 'Gophna', 31.96, 35.22, 'judeans', 0, 1, { terrain: 'hills' }],
    ['jerusalem', 'Jerusalem', 31.78, 35.23, 'seleucids', 1, 3, { garrison: 2000, terrain: 'hills' }],
    ['bethhoron', 'Beth Horon', 31.88, 35.12, null, 0, 0, { terrain: 'mountains', narrows: true }],
    ['emmaus', 'Emmaus', 31.84, 34.99, null, 0, 1, { terrain: 'plains' }],
    ['bethzur', 'Beth Zur', 31.59, 35.08, 'seleucids', 1, 1, { terrain: 'hills' }],
    ['hebron', 'Hebron', 31.53, 35.1, 'idumea', 1, 1],
    ['jericho', 'Jericho', 31.86, 35.46, 'seleucids', 1, 1],
    ['samaria', 'Samaria', 32.28, 35.2, 'seleucids', 2, 2],
    ['galilee', 'Sepphoris', 32.75, 35.28, 'seleucids', 0, 2],
    ['gilead', 'Gilead', 32.3, 35.8, null, 0, 1, { terrain: 'hills' }],
    ['joppa', 'Joppa', 32.05, 34.75, 'seleucids', 1, 2],
    ['jamnia', 'Jamnia', 31.75, 34.71, 'seleucids', 1, 1],
    ['gaza', 'Gaza', 31.5, 34.47, 'seleucids', 2, 2],
    ['ptolemais', 'Ptolemais', 32.92, 35.08, 'seleucids', 2, 2],
    ['damascus', 'Damascus', 33.51, 36.29, 'seleucids', 1, 3],
    ['tyre', 'Tyre', 33.27, 35.2, 'seleucids', 2, 2],
  ],
  armies: [
    ['judeans', 'gophna', 4500, 'Judah Maccabee', 5, { hero: true, id: 'judah' }],
    ['seleucids', 'samaria', 3000, 'Apollonius', 2, { id: 'apollonius', temper: 'rash', target: 'gophna' }],
    ['seleucids', 'damascus', 25000, 'Lysias', 3, { id: 'lysias', stay: true }],
    ['idumea', 'hebron', 2500, 'the Idumeans', 2, { id: 'idumeans', stay: true }],
  ],
  wars: [['judeans', 'seleucids']],
  allies: [['seleucids', 'idumea']],
  plans: ['charge', 'hold', 'narrows', 'ambush', 'feint', 'refuse'],
  cards: [
    {
      id: 'sabbath', at: 0, title: 'The Sabbath', art: 'uprising',
      text: 'Royal soldiers attacked a group of refugees in the desert on the Sabbath. They would not fight on the holy day, and a thousand were killed. Your father must decide: will his men defend themselves on the Sabbath?',
      options: [
        { label: 'Defend yourselves, even on the Sabbath', fx: { morale: 10 }, hint: 'Live to keep the law another day' },
        { label: 'Keep the Sabbath rest', fx: { men: -800, will: 4 }, hint: 'Faithful to the letter, and open to attack' },
      ],
      pick: 0, advise: 0,
      history: 'Mattathias and his followers decided that they would fight if attacked on the Sabbath, rather than all die and let their law perish with them.',
    },
    {
      id: 'emmaus', at: 2, title: 'The night raid', art: 'battle',
      text: 'Gorgias has slipped out of the royal camp at night with 5,000 foot and 1,000 horse to fall on your camp. Your scouts have seen him go.',
      options: [
        { label: 'Leave the camp empty and strike his', fx: { chance: 0.8, win: { gold: 50, sides: { seleucids: { will: -12 } }, log: 'Judah falls on the royal camp at Emmaus and burns it; Gorgias returns to find it in flames, and his men flee' }, lose: { men: -0.25, log: 'Gorgias finds you on the march' } }, hint: 'A game of hide and seek in the dark' },
        { label: 'Wait for him in your camp', fx: { chance: 0.35, win: { sides: { seleucids: { will: -6 } }, log: 'The raid breaks on your camp' }, lose: { men: -0.35, log: 'Gorgias’s raid catches your men in their tents' } }, hint: 'Defend what you have' },
      ],
      pick: 0, advise: 0,
      history: 'Judah left his camp empty and marched through the night on the main royal camp at Emmaus, which he burned. When Gorgias came back from finding nothing, his men saw the smoke and fled.',
    },
    {
      id: 'temple', from: 3, until: 5, if: (q) => q.owns('judeans', 'jerusalem'), title: 'The Temple', art: 'built',
      text: 'Jerusalem is yours, though the king’s men still hold its citadel. The Temple is defiled and overgrown. Your men want it cleansed and rededicated at once.',
      options: [
        { label: 'Cleanse and rededicate the Temple', fx: { will: 15, gold: -20 }, hint: 'A feast of eight days, and a people renewed' },
        { label: 'Storm the citadel first', fx: { men: -800, sides: { seleucids: { will: -5 } } }, hint: 'Finish the soldiers before the ceremonies' },
      ],
      pick: 0, advise: 0,
      history: 'Judah had the Temple cleansed and rededicated in December 164 BC, with eight days of celebration: the festival of Hanukkah remembers it. The citadel held out for another twenty years.',
    },
    {
      id: 'galilee', at: 4, title: 'Cries from Galilee', art: 'expedition',
      text: 'Messengers come from Galilee and from Gilead across the Jordan: the Jews there are under attack by their neighbours. Going to their aid would take your army far from Judea.',
      options: [
        { label: 'Send Simon to Galilee, and go to Gilead yourself', fx: { will: 8, men: -0.08 }, hint: 'Rescue them, and bring them home to Judea' },
        { label: 'Stay and guard Judea', fx: { will: -6 }, hint: 'Safe, and bitter' },
      ],
      pick: 0, advise: 0,
      history: 'Simon marched to Galilee and Judah crossed the Jordan to Gilead. They brought the Jewish communities back to Judea with them.',
    },
    {
      id: 'rome', at: 6, title: 'Envoys to Rome', art: 'charter',
      text: 'Far to the west, Rome has humbled Macedon and the Seleucids alike. A treaty of friendship with Rome might make the king think twice.',
      options: [
        { label: 'Send envoys to Rome', fx: { sides: { seleucids: { will: -8 } } }, hint: 'A powerful friend, far away' },
        { label: 'Trust in your own swords', fx: { morale: 5 }, hint: 'Rome helps no one for nothing' },
      ],
      pick: 0, advise: 0,
      history: 'Judah sent Eupolemus and Jason to Rome, which signed a treaty of friendship with the Jews in 161 BC. It sent no soldiers.',
    },
    {
      id: 'elasa', at: 7, if: (q) => !!q.army('bacchides'), title: 'Bacchides', art: 'fallen',
      text: 'Bacchides has come with 20,000 men and 2,000 horse. Most of your army has slipped away in fear; 800 stay. Your men beg you to withdraw and fight another day.',
      options: [
        { label: 'Withdraw to the wilderness', fx: { will: -6, move: ['judah', 'jericho'] }, hint: 'Live, and fight on later' },
        { label: '“If our time has come, let us die bravely”', fx: { morale: 20 }, hint: 'Stand with the 800' },
      ],
      pick: 1, advise: 0,
      history: 'Judah refused to flee: “If our time has come, let us die bravely for our people.” He broke the right wing of Bacchides’s army, but was killed. His brothers Jonathan and Simon carried on.',
    },
  ],
  events: [
    { id: 'seron', at: 1, side: 'seleucids', fx: { spawn: ['seleucids', 'joppa', 6000, 'Seron', 2, { id: 'seron', temper: 'rash', target: 'gophna' }] }, text: 'Seron, commander in Syria, marches up from the coast to make his name by crushing the rebels', sides: ['seleucids'] },
    { id: 'gorgias', at: 2, side: 'seleucids', fx: { spawn: ['seleucids', 'jamnia', 20000, 'Nicanor and Gorgias', 3, { id: 'gorgias', target: 'gophna' }] }, text: 'Lysias sends Nicanor and Gorgias with 20,000 men to crush the revolt; slave dealers follow the army to buy the prisoners', sides: ['seleucids'] },
    { id: 'lysias', at: 3, side: 'seleucids', fx: { free: ['lysias'], aim: { lysias: 'jerusalem' } }, text: 'The regent Lysias himself marches south', sides: ['seleucids'] },
    { id: 'antiochus', at: 3, side: 'seleucids', fx: { will: -12 }, text: 'King Antiochus IV dies on campaign in Persia; his son is a boy, and rivals gather', sides: ['seleucids'] },
    { id: 'home1', at: 4, side: 'seleucids', fx: { then: (s) => { for (const id of ['gorgias', 'seron', 'lysias']) delete s.armies[id]; } }, text: 'What is left of the royal armies goes home to Syria for the winter', sides: ['seleucids'] },
    { id: 'elephants', at: 4, side: 'seleucids', fx: { spawn: ['seleucids', 'bethzur', 40000, 'Lysias and the elephants', 3, { id: 'elephants', target: 'jerusalem', temper: 'bold' }] }, text: 'Lysias returns with a great army and war elephants', sides: ['seleucids'] },
    { id: 'philip', at: 5, if: (q) => q.alive('judeans'), side: 'seleucids', fx: { will: -18, remove: 'elephants' }, text: 'News comes that Philip has seized Antioch: Lysias hurries home and offers the Jews their law', sides: ['seleucids'] },
    { id: 'nicanor', at: 6, side: 'seleucids', fx: { spawn: ['seleucids', 'samaria', 9000, 'Nicanor', 3, { id: 'nicanor', temper: 'rash', target: 'gophna' }], will: 8 }, text: 'King Demetrius sends Nicanor to finish Judah', sides: ['seleucids'] },
    { id: 'bacchides', at: 7, side: 'seleucids', fx: { spawn: ['seleucids', 'samaria', 22000, 'Bacchides', 4, { id: 'bacchides', temper: 'bold' }], will: 10, then: (s) => { const j = s.armies.judah; if (j) j.men = Math.min(j.men, 3000); } }, text: 'Bacchides comes with 20,000 foot and 2,000 horse; Judah’s men desert him in fear', sides: ['seleucids', 'judeans'] },
  ],
};
