// The Persian Wars, 490–479 BC: Athens and its allies against the Persian Empire, from Marathon to Plataea.
const GREECE = ['attica', 'marathon', 'plataea', 'salamis', 'megara', 'corinth', 'sparta', 'elis', 'aegina', 'euboea', 'artemisium', 'delphi', 'boeotia', 'thermopylae'];

export default {
  id: 'persian', n: 1, era: 'The ancient world', age: 'ancient',
  title: 'The Persian Wars', years: '490–479 BC',
  you: 'greeks',
  hero: { name: 'Themistocles', title: 'statesman and general of Athens', look: 'hellenic' },
  advisor: { name: 'Aristides', title: 'called the Just', look: 'hellenic' },
  court: [{ id: 'aristides', name: 'Aristides', title: 'called the Just', look: 'hellenic' }, { id: 'xanthippus', name: 'Xanthippus', title: 'general of Athens', look: 'hellenic', from: 2 }],
  hook: 'Save Greece from the greatest empire on earth, at Marathon, Thermopylae and Salamis.',
  art: 'war',
  brief: [
    'Summer 490 BC. The Persian Empire rules from Egypt to India. When the Greek cities of Ionia rebelled against it, Athens sent them ships, and they burned Sardis. King Darius has not forgotten.',
    'A Persian fleet has burned Eretria and landed an army at Marathon, a day’s march from Athens, guided by Hippias, the tyrant Athens drove out. You are Themistocles of Athens, and the Greek cities that will fight, Sparta first among them, look to you. Behind this first army a far greater one is coming.',
  ],
  goal: { kind: 'drive', foe: 'persia', provs: GREECE, count: 9, early: 8, text: 'Drive the Persians out of Greece', won: 'No Persian army stands in Greece: the Greeks are free' },
  lose: { will: 'Athens has lost heart and submits to the Great King', time: 'The Persians still stand in Greece when the fighting season ends' },
  loseCapital: false,
  history: {
    won: true, at: 8,
    text: 'The Greeks won. Athens beat the first army at Marathon in 490 BC. Ten years later Xerxes came with a vast army; Leonidas died holding Thermopylae and Athens was burned, but the fleet Themistocles had built destroyed the Persian navy at Salamis. In 479 BC the Greeks crushed the last Persian army at Plataea and its fleet at Mycale. Persia never invaded Greece again.',
    better: 'Win without Athens ever falling to the Persians.',
    judge: (q, s, won) => (won ? (q.flag('burned') ? 'as' : 'better') : 'worse'),
  },
  view: [35.6, 19.6, 41.9, 29.6],
  reach: 80,
  turns: ['Summer 490 BC', 'Autumn 490 BC', 'Spring 487 BC', 'Spring 483 BC', 'Spring 481 BC', 'Summer 480 BC', 'Autumn 480 BC', 'Spring 479 BC', 'Summer 479 BC', 'Autumn 479 BC', 'Spring 478 BC'],
  meanwhile: [
    'A Persian fleet under Datis and Artaphernes burns Eretria, then lands at the bay of Marathon. Athens sends the runner Pheidippides to ask Sparta for help.',
    'At Marathon the Athenians and Plataeans under Miltiades charge the Persian line and drive it into the sea. The Spartans arrive the day after the battle.',
    'Darius dies in 486 BC before he can avenge Marathon. His son Xerxes must first put down a revolt in Egypt. Athens and Aegina fight a war at sea.',
    'A rich new vein of silver is found at Laurium. Themistocles persuades the Athenians to spend it on 200 warships instead of sharing it out.',
    'Xerxes gathers an enormous army and fleet at Sardis. Thirty-one Greek cities swear an alliance under Spartan command; others, Thebes and Thessaly among them, submit to Persia.',
    'Xerxes crosses the Hellespont on a bridge of boats. Leonidas and his 300 Spartans hold the pass of Thermopylae for three days and die there. Athens is evacuated and burned.',
    'Themistocles lures the Persian fleet into the narrow strait of Salamis, where it is shattered. Xerxes goes home, leaving Mardonius with an army in Greece.',
    'Mardonius winters in Thessaly and offers Athens generous terms to change sides. Athens refuses and is occupied a second time.',
    'At Plataea the Greek army under the Spartan Pausanias destroys Mardonius’s army. On the same day, it is said, the Greek fleet wins at Mycale in Ionia.',
    'The Athenians besiege and take Sestos on the Hellespont. The Greek cities of Ionia rise against Persia.',
    'Pausanias takes Byzantion. Athens founds the Delian League to carry on the war, and its own empire begins.',
  ],
  sides: {
    greeks: { name: 'The Greeks', short: 'Greeks', heirs: ['Aristides'], color: '#27466e', leader: 'Themistocles of Athens, with Sparta and the allied cities', capital: 'attica', gold: 160, will: 70, quality: 1.25, horse: 0.04, fleet: 1, levy: 6000, income: 15, tech: ['hoplites'], weariness: 0.6, persona: 'Athens, Sparta and the free Greek cities: quarrelsome allies, proud of their hoplites.' },
    persia: { name: 'The Persian Empire', short: 'Persia', heirs: ['Mardonius'], color: '#8c5a2b', leader: 'King Darius', capital: 'sardis', gold: 400, will: 80, quality: 0.7, horse: 0.3, fleet: 3, levy: 15000, income: 60, raiseFrom: 6, ai: 'bold', persona: 'The Great King of Persia: ruler of the world from the Aegean to the Indus, who means to punish Athens for burning Sardis.' },
    thebes: { name: 'Thebes', color: '#4f6b3a', leader: 'the oligarchs of Thebes', capital: 'boeotia', gold: 40, will: 50, quality: 1.05, horse: 0.15, levy: 4000, tech: ['hoplites'], ai: 'cautious', persona: 'The oligarchs of Thebes: rivals of Athens, ready to side with Persia.' },
    thessaly: { name: 'Thessaly', color: '#7a6a45', leader: 'the Aleuad lords', capital: 'thessaly', gold: 40, will: 45, quality: 0.9, horse: 0.45, levy: 4000, ai: 'cautious', persona: 'The horse lords of Thessaly, who will bow to whoever comes south with the bigger army.' },
    macedon: { name: 'Macedon', color: '#6b4a8c', leader: 'King Alexander I', capital: 'macedon', gold: 40, will: 40, quality: 0.9, horse: 0.3, levy: 3000, ai: 'cautious', persona: 'Alexander I of Macedon, Persia’s vassal, a secret friend of the Greeks.' },
    argos: { name: 'Argos', color: '#8a7a5a', leader: 'the Argives', capital: 'argos', gold: 40, will: 40, quality: 1.0, horse: 0.05, levy: 3000, ai: 'cautious', persona: 'Argos, Sparta’s old enemy, which stays out of the war.' },
  },
  provinces: [
    // Greece
    ['attica', 'Athens', 37.97, 23.73, 'greeks', 2, 4],
    ['marathon', 'Marathon', 38.15, 23.96, 'greeks', 0, 1, { terrain: 'plains' }],
    ['salamis', 'Salamis', 37.94, 23.49, 'greeks', 0, 1],
    ['plataea', 'Plataea', 38.22, 23.27, 'greeks', 1, 1],
    ['megara', 'Megara', 37.99, 23.35, 'greeks', 1, 1],
    ['corinth', 'Corinth', 37.91, 22.88, 'greeks', 2, 3],
    ['sparta', 'Sparta', 37.07, 22.43, 'greeks', 0, 3],
    ['elis', 'Elis', 37.89, 21.37, 'greeks', 0, 1],
    ['aegina', 'Aegina', 37.75, 23.43, 'greeks', 1, 2],
    ['argos', 'Argos', 37.63, 22.72, 'argos', 2, 2],
    ['euboea', 'Eretria', 38.39, 23.79, 'greeks', 1, 2],
    ['artemisium', 'Histiaea', 38.95, 23.1, 'greeks', 0, 1],
    ['delphi', 'Delphi', 38.48, 22.5, 'greeks', 0, 1],
    ['boeotia', 'Thebes', 38.32, 23.32, 'thebes', 2, 2],
    ['thermopylae', 'Thermopylae', 38.8, 22.54, null, 0, 0, { terrain: 'mountains', narrows: true }],
    ['thessaly', 'Larissa', 39.64, 22.42, 'thessaly', 1, 2, { terrain: 'plains' }],
    ['macedon', 'Aegae', 40.48, 22.32, 'macedon', 1, 2],
    ['potidaea', 'Potidaea', 40.19, 23.33, 'persia', 1, 1],
    // Thrace, the Hellespont and Asia
    ['doriscus', 'Doriscus', 40.87, 26.1, 'persia', 1, 1],
    ['sestos', 'Sestos', 40.23, 26.4, 'persia', 1, 1],
    ['byzantion', 'Byzantion', 41.01, 28.98, 'persia', 1, 3],
    ['abydos', 'Abydos', 40.19, 26.53, 'persia', 1, 1],
    ['dascylium', 'Dascylium', 40.28, 28.04, 'persia', 1, 2],
    ['lesbos', 'Mytilene', 39.11, 26.55, 'persia', 1, 2],
    ['sardis', 'Sardis', 38.49, 28.04, 'persia', 2, 4],
    ['ephesus', 'Ephesus', 37.94, 27.34, 'persia', 1, 2],
    ['miletus', 'Miletus', 37.53, 27.28, 'persia', 1, 2],
    ['samos', 'Samos', 37.69, 26.98, 'persia', 1, 2],
    ['naxos', 'Naxos', 37.1, 25.38, 'persia', 1, 2],
  ],
  sea: [['naxos', 'marathon'], ['naxos', 'euboea'], ['naxos', 'samos'], ['naxos', 'aegina'], ['lesbos', 'abydos'], ['lesbos', 'ephesus'], ['aegina', 'attica'], ['artemisium', 'thessaly'], ['potidaea', 'artemisium']],
  straits: [['abydos', 'sestos'], ['byzantion', 'doriscus'], ['byzantion', 'dascylium'], ['salamis', 'attica'], ['salamis', 'megara'], ['euboea', 'boeotia'], ['samos', 'ephesus']],
  armies: [
    ['greeks', 'attica', 11000, 'Miltiades', 4, { id: 'athenians' }],
    ['greeks', 'sparta', 8000, 'King Leonidas', 4, { id: 'spartans' }],
    ['persia', 'marathon', 25000, 'Datis', 3, { id: 'datis', temper: 'steady' }],
    ['persia', 'sardis', 20000, 'Artaphernes', 3, { id: 'artaphernes', stay: true }],
    ['thebes', 'boeotia', 7000, 'the Theban oligarchs', 2, { id: 'thebans', stay: true }],
    ['thessaly', 'thessaly', 5000, 'the Aleuads', 2, { id: 'thessalians', stay: true }],
    ['macedon', 'macedon', 4000, 'Alexander I', 3, { id: 'macedonians', stay: true }],
    ['argos', 'argos', 5000, 'the Argives', 2, { id: 'argives', stay: true }],
  ],
  wars: [['greeks', 'persia']],
  allies: [['persia', 'macedon']],
  cards: [
    {
      id: 'marathon', at: 0, title: 'The Persians at Marathon', art: 'battle',
      text: 'Datis has landed some 25,000 men at the bay of Marathon, with the old tyrant Hippias as his guide. Your ten generals are split: half want to wait behind the walls for the Spartans, who come only after their festival. Miltiades wants to attack at once.',
      options: [
        { label: 'Attack at once, at a run', fx: { morale: 15 }, hint: 'Your hoplites will cross the last stretch at a run, before the Persian archers can find their range. Order the army onto Marathon, with strong wings' },
        { label: 'Wait behind the walls for the Spartans', fx: { will: -4 }, hint: 'Safe, but the Persian fleet may sail round to Athens while you wait' },
      ],
      pick: 0, advise: 0,
      history: 'Miltiades won the vote to fight. The Athenians thinned their centre, massed their wings and charged at a run. The wings won and closed in: some 6,400 Persians died, and 192 Athenians.',
    },
    {
      id: 'silver', at: 3, title: 'The silver of Laurium', art: 'built',
      text: 'Miners at Laurium have struck a rich vein of silver. The custom is to share it out among the citizens, ten drachmas each. Themistocles says Persia will return, and that the silver should build ships.',
      options: [
        { label: 'Build two hundred warships', fx: { fleet: 3, gold: -30, flag: 'fleet' }, hint: 'A navy to face Persia at sea' },
        { label: 'Share it among the citizens', fx: { gold: 60, will: 5 }, hint: 'The people will love you, for now' },
      ],
      pick: 0, advise: 0,
      history: 'Themistocles talked the Assembly into building 200 triremes, officially for the war with Aegina. Three years later that fleet saved Greece at Salamis.',
    },
    {
      id: 'league', at: 4, title: 'The congress at Corinth', art: 'charter',
      text: 'Sparta calls the Greek cities to Corinth to swear an alliance against Persia, under Spartan command. Athens has more ships than all the others together: should it give the command at sea to a Spartan too?',
      options: [
        { label: 'Yield the command, for unity', fx: { will: 12 }, hint: 'The Greeks stand together' },
        { label: 'Demand the command of the fleet', fx: { will: -8, morale: -10 }, hint: 'Pride, and a divided alliance' },
      ],
      pick: 0, advise: 0,
      history: 'Athens let the Spartan Eurybiades command the allied fleet, though most of its ships were Athenian. Unity mattered more.',
    },
    {
      id: 'oracle', at: 5, title: 'The wooden wall', art: 'court',
      text: 'The priestess at Delphi warns Athens to flee to the ends of the earth, and to trust in “the wooden wall”. Some say it means the old fence round the Acropolis. Themistocles says the wooden wall is the fleet.',
      options: [
        { label: 'Abandon the city and trust the ships', fx: { flag: 'evacuate' }, hint: 'The people escape to Salamis and Troezen; the city may burn, but Athens lives on in its ships' },
        { label: 'Defend the Acropolis', fx: { men: 4000 }, hint: 'Every man in the city stands to arms' },
      ],
      pick: 0, advise: 0,
      history: 'The Athenians read the oracle as Themistocles did. They sent their families to Salamis and Troezen and manned the ships. The few who stayed on the Acropolis died when the Persians burned it.',
    },
    {
      id: 'pass', at: 5, title: 'The pass of Thermopylae', art: 'battle',
      text: 'Xerxes’s army comes south along the coast. At Thermopylae the road between the mountains and the sea is only a few paces wide. King Leonidas of Sparta offers to hold it with a small force, while the fleet holds the strait of Artemisium.',
      options: [
        { label: 'Hold the pass', fx: { spawn: ['greeks', 'thermopylae', 7000, 'Leonidas and his 300', 5, { id: 'leonidas' }], flag: 'pass' }, hint: 'Leonidas and 7,000 Greeks stand at the narrows: order them to hold, and choose “hold the narrows” if attacked' },
        { label: 'Fall back to the Isthmus', fx: { will: -6 }, hint: 'Give up central Greece without a fight' },
      ],
      pick: 0, advise: 0,
      history: 'Leonidas held the pass for three days with about 7,000 men, until a local man, Ephialtes, showed the Persians a mountain path round it. Leonidas sent most of the army away and died with his 300 Spartans and the Thespians and Thebans who stayed.',
    },
    {
      id: 'salamis', at: 6, title: 'The strait of Salamis', art: 'war',
      text: 'The Persian fleet outnumbers yours two to one. The Spartans want to fall back to the Isthmus of Corinth. Themistocles wants to fight in the narrow strait of Salamis, where numbers count for little, and could send a secret message to lure Xerxes in.',
      options: [
        { label: 'Lure them into the strait', fx: { chance: 0.75, win: { flag: 'salamis', will: 15, sides: { persia: { will: -25, fleet: 0 } }, log: 'The Persian fleet is shattered in the strait of Salamis' }, lose: { will: -10, fleet: 0, log: 'The battle in the strait goes against you' } }, hint: 'Fight where their numbers do them no good' },
        { label: 'Fall back to the Isthmus', fx: { chance: 0.3, win: { flag: 'salamis', will: 8, sides: { persia: { will: -15, fleet: 0 } }, log: 'The fleets clash off the Isthmus and the Persians are beaten' }, lose: { will: -15, log: 'The allied fleet breaks up as each city sails home' } }, hint: 'Fight in open water, or not at all' },
      ],
      pick: 0, advise: 0, if: (q) => q.flag('fleet'),
      history: 'Themistocles sent his slave Sicinnus to tell Xerxes the Greeks were about to flee. Xerxes blocked the strait and attacked at dawn; in the narrows his ships fouled each other and were rammed. He watched from a throne on the shore, and went home to Asia.',
    },
    {
      id: 'terms', at: 7, if: (q) => q.alive('persia'), title: 'An offer from Mardonius', art: 'peace',
      text: 'King Alexander of Macedon brings Mardonius’s terms: Athens may keep its land, rebuild its temples at Persia’s cost and rule whom it likes, if it changes sides. Sparta’s envoys beg you to refuse.',
      options: [
        { label: 'Refuse', fx: { will: 8 }, hint: 'Stay with the Greeks, whatever it costs' },
        { label: 'Accept', fx: { end: 'lose', why: 'Athens made peace with Persia and betrayed the Greeks' }, hint: 'Safety for Athens, and shame for ever' },
      ],
      pick: 0, advise: 0,
      history: 'Athens refused: “As long as the sun keeps its course, we will never make terms with Xerxes.” Mardonius occupied Athens a second time.',
    },
    {
      id: 'mycale', at: 8, if: (q) => q.flag('salamis'), title: 'Ionia calls', art: 'expedition',
      text: 'Envoys from Samos beg the Greek fleet to cross the Aegean: if it comes, the Greeks of Ionia will rise against Persia. The Persian ships are drawn up on the beach at Mycale.',
      options: [
        { label: 'Cross to Ionia', fx: { chance: 0.7, win: { give: [['samos', 'greeks']], sides: { persia: { will: -15 } }, log: 'The Greeks storm the camp at Mycale and burn the Persian fleet' }, lose: { will: -5, log: 'The landing at Mycale is thrown back' } }, hint: 'Carry the war to Asia' },
        { label: 'Stay in Greek waters', fx: {}, hint: 'Guard what you have' },
      ],
      pick: 0, advise: 0,
      history: 'The Greek fleet crossed to Mycale, stormed the Persian camp and burned the beached ships. The Ionians changed sides during the battle.',
    },
  ],
  events: [
    { id: 'runners', at: 1, fx: { spawn: ['greeks', 'megara', 2000, 'the Spartan vanguard', 3, { id: 'vanguard' }] }, text: 'Two thousand Spartans arrive from the south, after their festival', sides: ['greeks'] },
    { id: 'withdraw', at: 2, side: 'persia', fx: { then: (s) => { for (const a of Object.values(s.armies)) if (a.side === 'persia') { a.at = 'sardis'; a.from = 'sardis'; a.stay = true; } } }, text: 'The Persian fleet carries what is left of Datis’s army home to Asia', sides: ['persia'] },
    { id: 'miltiades', at: 2, if: (q) => q.living('Miltiades'), side: 'greeks', fx: { kill: 'Miltiades', succeed: { Miltiades: ['Xanthippus', 3] } }, text: 'Miltiades, the victor of Marathon, dies of a wound taken at Paros, in disgrace; Xanthippus takes his command', sides: ['greeks'] },
    { id: 'darius', at: 2, side: 'persia', fx: { will: 5, kill: 'King Darius', leader: 'King Xerxes' }, text: 'King Darius dies; his son Xerxes swears to finish what his father began', sides: ['persia'] },
    {
      id: 'xerxes', at: 5, side: 'persia', sides: ['persia', 'thebes', 'thessaly'],
      text: 'Xerxes crosses the Hellespont with the greatest army ever seen, and Thessaly and Thebes submit to him',
      fx: {
        spawn: [['persia', 'macedon', 150000, 'Xerxes', 3, { id: 'xerxes', target: 'attica' }], ['persia', 'potidaea', 25000, 'Mardonius', 4, { id: 'mardonius', target: 'attica' }]],
        rel: [['thebes', 'persia', 'ally'], ['thessaly', 'persia', 'ally'], ['thebes', 'greeks', 'war']],
        free: ['thebans', 'artaphernes', 'datis'], fleet: 3, will: 10,
      },
    },
    { id: 'ephialtes', at: 6, if: (q) => q.flag('pass') && q.at('greeks', 'thermopylae'), fx: { remove: 'leonidas', kill: 'King Leonidas', will: 8 }, text: 'Ephialtes shows the Persians a path round Thermopylae: Leonidas and his 300 die where they stand, and Greece will never forget them', sides: ['greeks', 'persia'] },
    { id: 'burned', if: (q) => q.owns('persia', 'attica') || q.owns('thebes', 'attica'), fx: { flag: 'burned', then: (s, q) => { if (q.flag('evacuate')) s.sides.greeks.will = Math.min(100, s.sides.greeks.will + 18); } }, text: 'The Persians burn Athens and the temples of the Acropolis', sides: ['greeks'] },
    {
      id: 'home', at: 7, if: (q) => q.flag('salamis'), side: 'persia', sides: ['persia'],
      text: 'Xerxes goes home to Asia with most of his army, leaving Mardonius and his best troops to finish the war',
      fx: { ai: 'steady', will: -10, then: (s) => {
        const x = s.armies.xerxes, m = s.armies.mardonius;
        if (x) { if (m) m.men += Math.round(x.men * 0.2); else { x.gen = 'Mardonius'; x.men = Math.round(x.men * 0.4); } if (m) delete s.armies.xerxes; }
      } },
    },
    { id: 'pausanias', at: 7, fx: { spawn: ['greeks', 'corinth', 38000, 'Pausanias', 4, { id: 'pausanias' }] }, text: 'Sparta at last marches north in strength: Pausanias leads the largest Greek army ever gathered', sides: ['greeks'] },
  ],
};
