// The Peloponnesian War, 431–404 BC: Sparta against the Athenian empire.
const ATHENS_EMPIRE = ['euboea', 'chalcidice', 'potidaea', 'hellespont', 'byzantion', 'lesbos', 'chios', 'samos', 'miletus', 'naxos', 'aegina'];

export default {
  id: 'sparta', n: 2, era: 'The ancient world', age: 'ancient',
  title: 'Wrath of Sparta', years: '431–404 BC',
  you: 'sparta',
  hero: { name: 'King Archidamus', title: 'King of Sparta, and after him King Agis', look: 'hellenic' },
  advisor: { name: 'Brasidas', title: 'the boldest of your officers', look: 'hellenic' },
  court: [{ id: 'lysander', name: 'Lysander', title: 'admiral of Sparta', look: 'hellenic', from: 13 }, { id: 'brasidas', name: 'Brasidas', title: 'the boldest of your officers', look: 'hellenic' }, { id: 'alcibiades', name: 'Alcibiades', title: 'an Athenian exile', look: 'hellenic', from: 8, until: 10 }],
  hook: 'The finest soldiers in Greece against the greatest navy: break the Athenian empire.',
  art: 'siege',
  brief: [
    'Spring 431 BC. Fifty years after the Persians were driven out, Athens has turned its alliance into an empire. Its tribute pays for 300 warships, and behind its Long Walls it cannot be starved while it rules the sea. Corinth and Thebes beg you to act.',
    'You are Sparta. On land no army in Greece can face your hoplites, but Athens will not fight you on land. You must break its empire, its fleet or its will. It will take a generation.',
  ],
  goal: {
    kind: 'custom', text: 'Make Athens surrender', won: 'Athens surrenders: its walls come down and its empire is yours to dissolve',
    check: (q, s) => {
      const fleet = s.sides.athens.fleet, will = s.sides.athens.will;
      return { met: s.prov.attica.owner === 'sparta' || (will <= 25 && fleet === 0) || !s.sides.athens.alive, progress: Math.min(1, (100 - will) / 75) * (fleet ? 0.6 : 1), text: `Athens’s will to fight: ${Math.round(will)}; its fleet ${fleet ? 'still rules the sea' : 'is gone'}. Athens gives in when both are broken, or when it falls` };
    },
  },
  lose: { will: 'Sparta has lost heart and makes peace, and the Athenian empire stands', capital: 'Sparta itself has fallen' },
  history: {
    won: true, at: 15,
    text: 'Sparta won, after twenty-seven years. Athens survived the plague and its great invasions, but lost its army in Sicily in 413 BC. With Persian gold, Sparta built a fleet; Lysander destroyed the Athenian navy at Aegospotami in 405 BC, and starving Athens surrendered in 404 BC. Its walls were pulled down.',
    better: 'Bring Athens to surrender sooner than it took Sparta.',
  },
  view: [35.9, 19.6, 41.4, 29.4],
  reach: 70,
  turns: ['Spring 431 BC', 'Summer 430 BC', 'Spring 429 BC', 'Summer 427 BC', 'Summer 425 BC', 'Winter 424 BC', 'Spring 421 BC', 'Summer 418 BC', 'Summer 415 BC', 'Autumn 413 BC', 'Summer 412 BC', 'Summer 411 BC', 'Spring 410 BC', 'Summer 407 BC', 'Autumn 406 BC', 'Autumn 405 BC', 'Spring 404 BC'],
  meanwhile: [
    'King Archidamus leads the Peloponnesian army into Attica and burns the farms. Pericles brings the country people inside the Long Walls and sends the fleet to raid the Peloponnese.',
    'A plague breaks out in crowded Athens. Over the next years it kills perhaps a quarter of the people.',
    'Pericles dies of the plague. Sparta lays siege to Plataea, Athens’s loyal ally.',
    'Athens crushes the revolt of Mytilene and, after a famous debate, cancels the order to kill all its men. Plataea surrenders, and its defenders are put to death.',
    'The Athenians fortify Pylos on Sparta’s own coast and trap 420 Spartans on the island of Sphacteria. When 292 of them surrender, all Greece is shocked.',
    'The Spartan Brasidas marches north and takes Amphipolis, Athens’s key city in Thrace. Thucydides, the Athenian general who failed to save it, is exiled and writes the war’s history.',
    'Brasidas and the Athenian Cleon both fall at Amphipolis. Nicias makes a peace that is meant to last fifty years.',
    'At Mantinea Sparta crushes Argos and its allies, in the largest land battle of the war.',
    'Athens sends a great fleet to conquer Sicily. Its general Alcibiades, recalled to face trial, flees to Sparta.',
    'On Alcibiades’s advice Sparta fortifies Decelea in Attica and sends Gylippus to Syracuse, where the whole Athenian expedition is destroyed.',
    'Athens’s allies in Ionia revolt, and Persia agrees to pay for a Spartan fleet in return for the Greek cities of Asia.',
    'Oligarchs seize power in Athens for a few months; the fleet at Samos stays loyal to the democracy.',
    'Alcibiades, back with Athens, destroys the Spartan fleet at Cyzicus. Sparta offers peace, and Athens refuses.',
    'Lysander takes command of the Spartan fleet and wins the friendship of Cyrus, the Persian king’s son, and his gold.',
    'Athens wins a great sea battle at Arginusae, then puts six of its victorious generals to death for failing to rescue the shipwrecked.',
    'Lysander catches the Athenian fleet beached at Aegospotami and captures almost all of it. Athens’s grain route is cut.',
    'Starving and besieged, Athens surrenders. Its Long Walls are pulled down to the music of flute-girls.',
  ],
  sides: {
    sparta: { name: 'Sparta and its allies', short: 'Sparta', heirs: ['King Agis'], color: '#9c2a1c', leader: 'King Archidamus', capital: 'sparta', gold: 90, will: 72, quality: 1.3, horse: 0.06, fleet: 0, levy: 6000, income: 10, tech: ['hoplites'], weariness: 0.6, persona: 'Sparta: the finest soldiers in Greece, slow, cautious and suspicious of the sea.' },
    athens: { name: 'Athens and its empire', short: 'Athens', heirs: ['Nicias'], color: '#27466e', leader: 'Pericles', capital: 'attica', gold: 400, will: 95, quality: 1.05, horse: 0.06, fleet: 3, levy: 4000, income: 50, tech: ['hoplites'], ai: 'cautious', weariness: 0.4, persona: 'Democratic Athens: rich, clever and restless; under Pericles it will not risk its army against Sparta on land, and trusts its fleet.' },
    argos: { name: 'Argos', color: '#8a7a5a', leader: 'the Argive democracy', capital: 'argos', gold: 40, will: 50, quality: 1.0, horse: 0.05, levy: 3000, tech: ['hoplites'], ai: 'cautious', persona: 'Argos, Sparta’s old rival in the Peloponnese, waiting for its chance.' },
    persia: { name: 'Persia', color: '#b3852c', leader: 'the satraps Tissaphernes and Pharnabazus', capital: 'sardis', gold: 300, will: 60, quality: 0.8, horse: 0.3, fleet: 2, levy: 4000, ai: 'cautious', persona: 'The Persian satraps of Asia Minor, who would pay Greeks to destroy each other and take back the cities of Ionia.' },
    macedon: { name: 'Macedon', color: '#6b4a8c', leader: 'King Perdiccas II', capital: 'macedon', gold: 40, will: 40, quality: 0.9, horse: 0.3, levy: 3000, ai: 'cautious', persona: 'Perdiccas of Macedon, who changes sides whenever it suits him.' },
  },
  provinces: [
    ['sparta', 'Sparta', 37.07, 22.43, 'sparta', 0, 3],
    ['messenia', 'Messenia', 37.18, 21.92, 'sparta', 0, 2],
    ['pylos', 'Pylos', 36.91, 21.69, 'sparta', 0, 1],
    ['cythera', 'Cythera', 36.15, 22.99, 'sparta', 0, 1],
    ['elis', 'Elis', 37.89, 21.37, 'sparta', 0, 1],
    ['arcadia', 'Tegea', 37.45, 22.42, 'sparta', 1, 1],
    ['argos', 'Argos', 37.63, 22.72, 'argos', 2, 2],
    ['corinth', 'Corinth', 37.91, 22.88, 'sparta', 2, 3],
    ['megara', 'Megara', 37.99, 23.35, 'sparta', 1, 1],
    ['boeotia', 'Thebes', 38.32, 23.32, 'sparta', 2, 2],
    ['plataea', 'Plataea', 38.22, 23.27, 'athens', 1, 1],
    ['delphi', 'Delphi', 38.48, 22.5, null, 0, 1],
    ['attica', 'Athens', 37.97, 23.73, 'athens', 3, 6, { port: true, garrison: 40000 }],
    ['decelea', 'Decelea', 38.17, 23.8, 'athens', 0, 2, { terrain: 'hills' }],
    ['aegina', 'Aegina', 37.75, 23.43, 'athens', 0, 1],
    ['euboea', 'Chalcis', 38.46, 23.6, 'athens', 1, 2],
    ['naupactus', 'Naupactus', 38.39, 21.83, 'athens', 1, 1],
    ['corcyra', 'Corcyra', 39.62, 19.92, 'athens', 2, 2],
    ['thessaly', 'Larissa', 39.64, 22.42, null, 0, 1, { terrain: 'plains' }],
    ['macedon', 'Pella', 40.76, 22.52, 'macedon', 1, 2],
    ['potidaea', 'Potidaea', 40.19, 23.33, 'athens', 2, 1],
    ['chalcidice', 'Amphipolis', 40.82, 23.85, 'athens', 1, 3],
    ['hellespont', 'Sestos', 40.23, 26.4, 'athens', 1, 2],
    ['lampsacus', 'Lampsacus', 40.35, 26.69, 'persia', 1, 1],
    ['byzantion', 'Byzantion', 41.01, 28.98, 'athens', 2, 3],
    ['lesbos', 'Mytilene', 39.11, 26.55, 'athens', 2, 2],
    ['chios', 'Chios', 38.37, 26.14, 'athens', 1, 2],
    ['samos', 'Samos', 37.69, 26.98, 'athens', 1, 2],
    ['miletus', 'Miletus', 37.53, 27.28, 'athens', 1, 2],
    ['sardis', 'Sardis', 38.49, 28.04, 'persia', 2, 4],
    ['naxos', 'Naxos', 37.1, 25.38, 'athens', 1, 2],
    ['melos', 'Melos', 36.72, 24.43, null, 1, 1],
  ],
  sea: [['attica', 'aegina'], ['attica', 'naxos'], ['attica', 'euboea'], ['naxos', 'samos'], ['naxos', 'melos'], ['naxos', 'chios'], ['chios', 'lesbos'], ['lesbos', 'hellespont'], ['attica', 'pylos'], ['attica', 'cythera'], ['naupactus', 'corcyra'], ['euboea', 'chalcidice'], ['corinth', 'naupactus'], ['melos', 'cythera'], ['samos', 'miletus']],
  straits: [['hellespont', 'lampsacus'], ['byzantion', 'hellespont'], ['chios', 'sardis'], ['potidaea', 'chalcidice'], ['euboea', 'boeotia'], ['aegina', 'megara'], ['naupactus', 'delphi']],
  armies: [
    ['sparta', 'arcadia', 30000, 'King Archidamus', 4, { hero: true, id: 'archidamus' }],
    ['sparta', 'boeotia', 8000, 'the Boeotians', 3, { id: 'boeotians' }],
    ['athens', 'attica', 16000, 'Pericles', 4, { id: 'pericles' }],
    ['athens', 'potidaea', 6000, 'the besiegers of Potidaea', 3, { id: 'potidaeans', stay: true }],
    ['athens', 'naupactus', 3000, 'Phormio', 4, { id: 'phormio' }],
    ['argos', 'argos', 6000, 'the Argives', 2, { id: 'argives', stay: true }],
    ['persia', 'sardis', 12000, 'Tissaphernes', 3, { id: 'tissaphernes', stay: true }],
    ['macedon', 'macedon', 4000, 'Perdiccas', 3, { id: 'perdiccas', stay: true }],
  ],
  wars: [['sparta', 'athens']],
  allies: [],
  cards: [
    {
      id: 'invade', at: 0, title: 'The invasion of Attica', art: 'raid',
      text: 'The Athenians have brought their country people inside the Long Walls. Their army will not come out to fight you. You can burn their farms and olive trees, but the city is fed from the sea.',
      options: [
        { label: 'Burn Attica every summer', fx: { sides: { athens: { will: -6, gold: -40 } } }, hint: 'Hurt their pride and their purses; a crowded city breeds disease' },
        { label: 'Strike at their allies instead', fx: { give: ['plataea', 'sparta'] }, hint: 'Plataea, Athens’s friend, is within reach' },
      ],
      pick: 0, advise: 0,
      history: 'Archidamus burned Attica nearly every summer. The Athenians watched from their walls; crowded together, they were struck by plague the next year.',
    },
    {
      id: 'sphacteria', at: 4, title: 'Trapped on Sphacteria', art: 'siege',
      text: 'The Athenians have built a fort at Pylos on your own coast, and their ships have cut off 420 Spartans on the island of Sphacteria. Your helots in Messenia grow restless. Athens might return the men for a peace.',
      options: [
        { label: 'Offer peace to save them', fx: { will: -6, sides: { athens: { will: 6 } } }, hint: 'Athens will refuse, and your weakness shows' },
        { label: 'Let them fight it out', fx: { chance: 0.3, win: { will: 4, log: 'The men on Sphacteria hold until Athens gives up the siege' }, lose: { will: -10, log: 'The Spartans on Sphacteria surrender: 292 are taken to Athens as hostages' } }, hint: 'A Spartan never surrenders; or so they say' },
      ],
      pick: 1, advise: 1,
      history: 'Athens refused peace and stormed the island. 292 men surrendered, 120 of them Spartan citizens, and all Greece was shocked that Spartans would give up. Athens held them as hostages against further invasions.',
    },
    {
      id: 'brasidas', at: 5, title: 'Brasidas goes north', art: 'expedition',
      text: 'Brasidas asks for 1,700 men, mostly freed helots and mercenaries, to march through Thessaly and stir up Athens’s cities in Thrace. The ephors think it reckless.',
      options: [
        { label: 'Send him', fx: { spawn: ['sparta', 'thessaly', 6000, 'Brasidas', 5, { id: 'brasidas', target: 'chalcidice', temper: 'bold' }] }, hint: 'Strike at the edge of the Athenian empire, where it is weakest' },
        { label: 'Keep your men at home', fx: { will: 3 }, hint: 'Safer, and slower' },
      ],
      pick: 0, advise: 0,
      history: 'Brasidas marched north, won over Acanthus with words and took Amphipolis, Athens’s richest city in Thrace. He died defending it in 422 BC, as did the Athenian Cleon, and the way to peace opened.',
    },
    {
      id: 'nicias', at: 6, if: (q) => q.war('sparta', 'athens'), title: 'The Peace of Nicias', art: 'peace',
      text: 'After ten years, both sides are tired. The Athenian Nicias proposes a peace for fifty years: each side gives back what it took, and the Sphacteria prisoners come home.',
      options: [
        { label: 'Make the peace', fx: { will: 10, rel: ['sparta', 'athens', 'peace'], flag: 'nicias' }, hint: 'Rest, and your men back; but Athens keeps its empire' },
        { label: 'Fight on', fx: { will: -6 }, hint: 'Keep the pressure on' },
      ],
      pick: 0, advise: 0,
      history: 'Sparta and Athens swore the Peace of Nicias in 421 BC. Many of Sparta’s allies refused to sign, and within a few years the two were fighting again.',
    },
    {
      id: 'alcibiades', at: 8, title: 'The Athenian at your door', art: 'turncoat',
      text: 'Alcibiades, the brilliant Athenian who planned the attack on Sicily, has fled his city to escape trial. He offers to tell you how to beat Athens: send help to Syracuse, and build a fort in Attica itself.',
      options: [
        { label: 'Take his advice', fx: { flag: 'alcibiades', will: 3 }, hint: 'He knows Athens as no Spartan can' },
        { label: 'Trust no Athenian', fx: {}, hint: 'A traitor once, a traitor twice' },
      ],
      pick: 0, advise: 0,
      history: 'Sparta took Alcibiades’s advice. It sent Gylippus to Syracuse and fortified Decelea in Attica. Alcibiades later betrayed Sparta too, and went back to Athens.',
    },
    {
      id: 'gylippus', at: 9, title: 'Syracuse begs for help', art: 'battle',
      text: 'A great Athenian fleet and army besiege Syracuse in Sicily. The Syracusans ask for a Spartan general to lead them.',
      options: [
        { label: 'Send Gylippus', fx: { chance: 0.75, win: { sides: { athens: { will: -25, fleet: -1 } }, will: 8, log: 'The Athenian expedition is destroyed at Syracuse' }, lose: { sides: { athens: { will: 8, gold: 200 } }, log: 'Syracuse falls to Athens, and Sicily’s grain is Athens’s' } }, hint: 'One man to lead a city' },
        { label: 'Leave Sicily to itself', fx: { chance: 0.35, win: { sides: { athens: { will: -20, fleet: -1 } }, log: 'Syracuse beats the Athenians alone' }, lose: { sides: { athens: { will: 10, gold: 200 } }, log: 'Syracuse falls to Athens' } }, hint: 'Keep your men in Greece' },
      ],
      pick: 0, advise: 0,
      history: 'Gylippus reached Syracuse in time. In 413 BC the whole Athenian force was destroyed: some 40,000 men lost, the generals Nicias and Demosthenes executed, the prisoners worked to death in the quarries.',
    },
    {
      id: 'decelea', at: 9, title: 'A fort in Attica', art: 'built',
      text: 'Alcibiades says: do not just raid Attica, stay there. A fort at Decelea, in sight of Athens, would cut it off from its silver mines and its farms the whole year round.',
      options: [
        { label: 'Fortify Decelea', fx: { give: ['decelea', 'sparta'], spawn: ['sparta', 'decelea', 8000, 'the garrison of Decelea', 3, { id: 'agis', stay: true }], sides: { athens: { gold: -120, will: -6 } } }, hint: 'Twenty thousand Athenian slaves will run to you' },
        { label: 'Keep raiding each summer', fx: {}, hint: 'The old way' },
      ],
      pick: 0, advise: 0,
      history: 'King Agis fortified Decelea in 413 BC. More than 20,000 slaves, many of them miners from the silver mines at Laurium, fled to the Spartans.',
    },
    {
      id: 'persia', at: 10, title: 'Persian gold', art: 'charter',
      text: 'The Persian satraps offer to pay for a Spartan fleet. Their price: the Greek cities of Asia, which Greeks freed from Persia seventy years ago, go back to the Great King.',
      options: [
        { label: 'Take the gold and build a fleet', fx: { fleet: 2, gold: 200, will: -4, rel: ['sparta', 'persia', 'ally'], sides: { persia: { ai: 'steady' } } }, hint: 'A fleet at last, and a stain on Sparta’s name' },
        { label: 'Refuse to sell Greeks to Persia', fx: { will: 5 }, hint: 'Honour, and no fleet' },
      ],
      pick: 0, advise: 0,
      history: 'Sparta took the deal. Persian money paid the crews of a Spartan fleet, and the Greek cities of Asia went back to Persia when the war was over.',
    },
    {
      id: 'aegospotami', from: 15, if: (q) => q.gold('sparta') >= 0 && q.alive('athens') && q.flag('fleet'), title: 'The goat rivers', art: 'war',
      text: 'Lysander’s fleet waits at Lampsacus. Across the strait, at Aegospotami, the Athenians beach their 180 ships each evening and scatter to find food. Alcibiades has warned them, and been ignored.',
      options: [
        { label: 'Strike when they scatter', fx: { chance: 0.8, win: { sides: { athens: { fleet: 0, will: -20 } }, will: 10, log: 'Lysander takes the Athenian fleet on the beach: 170 ships, and 3,000 prisoners' }, lose: { fleet: -1, log: 'The Athenians are ready, and your attack fails' } }, hint: 'A surprise, if you wait for the right evening' },
        { label: 'Offer battle at sea', fx: { chance: 0.4, win: { sides: { athens: { fleet: 0, will: -15 } }, log: 'The fleets meet and the Athenians are beaten' }, lose: { fleet: 0, will: -10, log: 'The Athenian fleet wins at sea' } }, hint: 'Fight them ship to ship' },
      ],
      pick: 0, advise: 0,
      history: 'Lysander waited four days, then struck while the crews were ashore. He captured about 170 ships and put some 3,000 Athenian prisoners to death. Athens had no fleet left.',
    },
  ],
  events: [
    { id: 'plague', at: 1, side: 'athens', fx: { then: (s) => { for (const a of Object.values(s.armies)) if (a.side === 'athens') a.men = Math.round(a.men * 0.72); }, will: -10 }, text: 'Plague breaks out in Athens, crowded behind its walls', sides: ['athens'] },
    { id: 'pericles', at: 2, if: (q) => q.living('Pericles'), side: 'athens', fx: { will: -6, ai: 'bold', leader: 'Cleon, and the Assembly', kill: 'Pericles', succeed: { Pericles: ['Cleon', 3] } }, text: 'Pericles dies of the plague. Bolder men lead the Assembly, and Cleon takes his army', sides: ['athens'] },
    { id: 'phormio', at: 3, if: (q) => q.living('Phormio'), side: 'athens', fx: { kill: 'Phormio', succeed: { Phormio: ['Asopius', 2] } }, text: 'Phormio, the best admiral of Athens, is dead; his son Asopius leads his men', sides: ['athens'] },
    { id: 'archidamus', at: 4, if: (q) => q.living('King Archidamus'), side: 'sparta', fx: { kill: 'King Archidamus', succeed: { 'King Archidamus': ['King Agis', 3] }, leader: 'King Agis' }, text: 'Old King Archidamus is dead. His son Agis is king of Sparta, and leads its army now', sides: ['sparta'] },
    { id: 'cleon', at: 6, if: (q) => q.living('Cleon'), side: 'athens', fx: { kill: 'Cleon', succeed: { Cleon: ['Nicias', 3] }, leader: 'Nicias, and the Assembly' }, text: 'Cleon falls in Thrace, at Amphipolis; the cautious Nicias leads Athens now', sides: ['athens'] },
    { id: 'syracuse', at: 10, if: (q) => q.living('Nicias') && q.living('Demosthenes'), side: 'athens', fx: { kill: ['Nicias', 'Demosthenes'], succeed: { Nicias: ['Thrasybulus', 4], Demosthenes: ['Thrasyllus', 3] }, leader: 'the Assembly, and its generals' }, text: 'Nicias and Demosthenes are put to death by the Syracusans; new generals lead Athens', sides: ['athens'] },
    { id: 'pylos', at: 4, side: 'athens', fx: { spawn: ['athens', 'pylos', 6000, 'Demosthenes', 4, { id: 'demosthenes' }], give: ['pylos', 'athens'] }, text: 'An Athenian fleet lands Demosthenes at Pylos, on Sparta’s own coast', sides: ['athens'] },
    { id: 'warAgain', at: 8, if: (q) => q.flag('nicias'), fx: { rel: ['sparta', 'athens', 'war'] }, text: 'The Peace of Nicias breaks down, and Sparta and Athens are at war again', sides: ['sparta', 'athens'] },
    { id: 'sicily', at: 8, side: 'athens', fx: { then: (s) => { const big = Object.values(s.armies).filter((a) => a.side === 'athens').sort((a, b) => b.men - a.men)[0]; if (big) big.men = Math.round(big.men * 0.5); } }, text: 'Athens sends half its army and a great fleet to conquer Sicily', sides: ['athens'] },
    { id: 'ionia', at: 10, if: (q) => q.ally('sparta', 'persia'), fx: { give: [['chios', 'sparta'], ['miletus', 'sparta']], flag: 'fleet', sides: { athens: { will: -8 } } }, text: 'Chios and Miletus revolt from Athens and open their harbours to the Spartan fleet', sides: ['sparta', 'athens'] },
    { id: 'cyzicus', at: 12, if: (q) => q.flag('fleet') && q.alive('athens'), fx: { fleet: -1, sides: { athens: { will: 8 } } }, text: 'Alcibiades, fighting for Athens again, destroys a Spartan fleet at Cyzicus', sides: ['athens', 'sparta'] },
    { id: 'lysander', at: 13, if: (q) => q.flag('fleet'), fx: { fleet: 2, gold: 150, spawn: ['sparta', 'chios', 8000, 'Lysander', 5, { id: 'lysander' }] }, text: 'Lysander takes command at sea; Cyrus, the Great King’s son, pays his crews', sides: ['sparta'] },
  ],
};
