// The end of the Han, 200–220: Cao Cao tries to reunite China.
export default {
  id: 'threekingdoms', n: 7, era: 'The ancient world', age: 'ancient',
  title: 'Three Kingdoms', years: '200–220',
  you: 'cao',
  hero: { name: 'Cao Cao', title: 'Imperial Chancellor of the Han', look: 'han' },
  advisor: { name: 'Guo Jia', title: 'your strategist', look: 'han' },
  court: [{ id: 'guojia', name: 'Guo Jia', title: 'your strategist', look: 'han', until: 2 }, { id: 'xunyu', name: 'Xun Yu', title: 'your chief minister', look: 'han', until: 6 }, { id: 'simayi', name: 'Sima Yi', title: 'your registrar', look: 'han', from: 7 }, { id: 'jiaxu', name: 'Jia Xu', title: 'a cunning adviser', look: 'han', from: 3 }],
  hook: 'Hold the last Han emperor in your hand, and make all China yours again.',
  art: 'war',
  brief: [
    'Autumn 200. The Han dynasty has collapsed into the wars of the warlords. You are Cao Cao. You hold the young Emperor Xian at Xuchang and rule in his name. A poet, a general and a ruthless politician.',
    'North of the Yellow River, Yuan Shao, the greatest warlord of all, has marched on you with more than 100,000 men. Beat him, and the north is yours. Then the south waits: Liu Biao on the Han river, young Sun Quan beyond the Yangtze, and the wandering Liu Bei, who calls himself a kinsman of the emperors.',
  ],
  goal: { kind: 'take', provs: ['ye', 'xiangyang', 'jiangling', 'wu', 'chengdu', 'hanzhong'], text: 'Reunite China: take Ye, Xiangyang, Jiangling, Wu, Chengdu and Hanzhong', won: 'All China bows to the Han throne, and to you' },
  lose: { hero: 'Cao Cao has fallen', will: 'Your officers lose faith, and the court turns on you', capital: 'Xuchang and the emperor are lost' },
  history: {
    won: false, at: 11,
    text: 'Cao Cao never reunited China. He crushed Yuan Shao at Guandu in 200 and made the whole north his, but in the winter of 208 Sun Quan and Liu Bei burned his fleet at the Red Cliffs on the Yangtze. He died in 220 as King of Wei. His son ended the Han dynasty; Liu Bei and Sun Quan made themselves emperors in the west and the south, and China stayed divided for sixty years: the Three Kingdoms.',
    better: 'Cross the Yangtze, and reunite China.',
  },
  view: [24.0, 101.5, 41.5, 123.0],
  reach: 230,
  turns: ['Autumn 200', 'Spring 202', 'Autumn 204', 'Summer 207', 'Autumn 208', 'Spring 209', 'Autumn 211', 'Spring 213', 'Summer 215', 'Spring 216', 'Spring 219', 'Spring 220'],
  meanwhile: [
    'At Guandu Cao Cao, outnumbered, burns Yuan Shao’s grain depot at Wuchao in a night raid, and Yuan Shao’s great army falls apart.',
    'Yuan Shao dies of an illness. His sons Yuan Tan and Yuan Shang fight each other for his inheritance.',
    'Cao Cao takes Ye, Yuan Shao’s capital, after flooding it by turning a river.',
    'Cao Cao crosses the wild north and crushes the Wuhuan at White Wolf Mountain. All of northern China is his.',
    'Liu Biao dies, and his son surrenders Jing province to Cao Cao. In the winter, at the Red Cliffs on the Yangtze, Zhou Yu and Liu Bei burn Cao Cao’s fleet with fire ships.',
    'Disease and defeat drive Cao Cao back north. Zhou Yu takes Jiangling; Liu Bei takes the south of Jing province.',
    'At Tong Pass Cao Cao defeats Ma Chao and Han Sui and wins the north-west.',
    'Cao Cao attacks Sun Quan at Ruxu and fails. “If I am to have a son,” he says, “let him be like Sun Quan.”',
    'Zhang Lu surrenders Hanzhong to Cao Cao. At Hefei, Zhang Liao with 800 men nearly captures Sun Quan.',
    'The emperor names Cao Cao King of Wei.',
    'Liu Bei takes Hanzhong. Guan Yu besieges Fancheng until Lü Meng of Wu seizes Jing province behind him; Guan Yu is captured and killed.',
    'Cao Cao dies in Luoyang. His son Cao Pi ends the Han dynasty and founds Wei; Liu Bei and Sun Quan soon call themselves emperors too. China stays divided for sixty years.',
  ],
  sides: {
    cao: { name: 'The house of Cao', short: 'Cao', heirs: ['Cao Pi'], color: '#27466e', leader: 'Cao Cao', capital: 'xuchang', gold: 120, will: 72, quality: 1.15, horse: 0.3, fleet: 0, levy: 15000, income: 20, weariness: 0.5, persona: 'Cao Cao, who rules in the emperor’s name: brilliant, suspicious and ruthless.' },
    yuan: { name: 'The house of Yuan', short: 'Yuan', heirs: ['Yuan Tan', 'Yuan Shang'], color: '#9a7a2a', leader: 'Yuan Shao, then his quarrelling sons', capital: 'ye', gold: 220, will: 75, quality: 0.9, horse: 0.3, levy: 15000, ai: 'bold', weariness: 1.2, persona: 'Yuan Shao, proud scion of a great clan, slow to decide and served by quarrelling advisers.' },
    jing: { name: 'Jing province', short: 'Jing', heirs: ['Liu Cong'], color: '#8c6b3f', leader: 'Liu Biao, governor of Jing', capital: 'xiangyang', gold: 120, will: 50, quality: 0.9, horse: 0.1, fleet: 2, levy: 8000, ai: 'cautious', persona: 'Liu Biao, an old scholar-governor who wants only to keep his province quiet.' },
    liu: { name: 'Liu Bei’s cause', short: 'Liu', heirs: ['Zhuge Liang', 'Guan Yu'], color: '#4f7a3a', leader: 'Liu Bei', capital: 'xinye', gold: 30, will: 70, quality: 1.05, horse: 0.2, levy: 4000, ai: 'cunning', persona: 'Liu Bei, a poor kinsman of the Han with famous sworn brothers, Guan Yu and Zhang Fei, and the strategist Zhuge Liang; never beaten for long.' },
    wu: { name: 'Wu', short: 'Wu', heirs: ['Lü Meng'], color: '#a3361f', leader: 'Sun Quan', capital: 'wu', gold: 160, will: 70, quality: 1.0, horse: 0.1, fleet: 3, levy: 8000, ai: 'steady', persona: 'Young Sun Quan of the lower Yangtze, guarded by his river and his fleet, with the brilliant Zhou Yu.' },
    shu: { name: 'Yi province', short: 'Yi', heirs: ['Liu Xun'], color: '#6b4a8c', leader: 'Liu Zhang of Yi province', capital: 'chengdu', gold: 120, will: 45, quality: 0.85, horse: 0.1, levy: 8000, ai: 'cautious', persona: 'Liu Zhang, weak ruler of the rich and mountain-walled west.' },
    liang: { name: 'The Liang warlords', short: 'Liang', heirs: ['Ma Chao', 'Han Sui'], color: '#5d7f86', leader: 'Ma Teng and Han Sui', capital: 'tianshui', gold: 60, will: 60, quality: 0.95, horse: 0.5, levy: 6000, ai: 'bold', persona: 'The horse-warlords of the north-west frontier.' },
  },
  provinces: [
    ['xuchang', 'Xuchang', 34.03, 113.85, 'cao', 2, 4],
    ['luoyang', 'Luoyang', 34.62, 112.45, 'cao', 2, 3],
    ['guandu', 'Guandu', 34.72, 114.0, 'cao', 0, 1, { terrain: 'plains' }],
    ['puyang', 'Puyang', 35.76, 115.03, 'cao', 1, 2],
    ['xuzhou', 'Pengcheng', 34.26, 117.18, 'cao', 1, 3],
    ['runan', 'Runan', 33.0, 114.3, 'cao', 0, 2],
    ['nanyang', 'Wan', 33.0, 112.53, 'cao', 1, 2],
    ['hefei', 'Hefei', 31.82, 117.23, 'cao', 2, 2],
    ['ye', 'Ye', 36.35, 114.35, 'yuan', 3, 4],
    ['baima', 'Liyang', 35.6, 114.5, 'yuan', 0, 1, { terrain: 'river' }],
    ['qingzhou', 'Linzi', 36.8, 118.3, 'yuan', 1, 2],
    ['bingzhou', 'Jinyang', 37.87, 112.55, 'yuan', 1, 2, { terrain: 'mountains' }],
    ['youzhou', 'Ji', 39.9, 116.4, 'yuan', 1, 2],
    ['xiangyang', 'Xiangyang', 32.01, 112.12, 'jing', 3, 3],
    ['xinye', 'Xinye', 32.52, 112.36, 'liu', 0, 1],
    ['jiangling', 'Jiangling', 30.35, 112.2, 'jing', 2, 3],
    ['chibi', 'The Red Cliffs', 29.87, 113.63, null, 0, 0, { terrain: 'river' }],
    ['changsha', 'Changsha', 28.2, 112.97, 'jing', 1, 2],
    ['chaisang', 'Chaisang', 29.7, 116.0, 'wu', 1, 2],
    ['jianye', 'Moling', 32.06, 118.78, 'wu', 2, 3],
    ['wu', 'Wu', 31.3, 120.6, 'wu', 2, 4],
    ['kuaiji', 'Kuaiji', 30.0, 120.58, 'wu', 0, 2],
    ['changan', 'Chang’an', 34.27, 108.94, 'liang', 2, 3],
    ['tianshui', 'Tianshui', 34.58, 105.72, 'liang', 1, 1],
    ['hanzhong', 'Hanzhong', 33.07, 107.03, 'shu', 2, 2, { terrain: 'mountains' }],
    ['chengdu', 'Chengdu', 30.66, 104.07, 'shu', 2, 4],
    ['badong', 'Baidi', 31.05, 109.5, 'shu', 1, 1, { terrain: 'mountains', narrows: true }],
  ],
  // the Yangtze: crossed only where the boats are, and only with a fleet
  cut: [['jiangling', 'changsha'], ['jiangling', 'chibi'], ['hefei', 'chaisang'], ['hefei', 'jianye'], ['xuzhou', 'jianye']],
  sea: [['jiangling', 'chibi'], ['hefei', 'jianye'], ['jiangling', 'changsha']],
  armies: [
    ['cao', 'guandu', 30000, 'Cao Cao', 5, { hero: true, id: 'caocao' }],
    ['cao', 'xuchang', 12000, 'Xiahou Dun', 3, { id: 'xiahou' }],
    ['cao', 'hefei', 8000, 'Zhang Liao', 5, { id: 'zhangliao', stay: true }],
    ['yuan', 'baima', 110000, 'Yuan Shao', 2, { id: 'yuanshao', target: 'xuchang' }],
    ['yuan', 'ye', 20000, 'Yuan Shang', 2, { id: 'yuanshang' }],
    ['jing', 'xiangyang', 40000, 'Liu Biao', 2, { id: 'liubiao', stay: true }],
    ['liu', 'xinye', 6000, 'Liu Bei', 4, { id: 'liubei', stay: true }],
    ['wu', 'chaisang', 30000, 'Zhou Yu', 5, { id: 'zhouyu', stay: true }],
    ['wu', 'wu', 20000, 'Sun Quan', 3, { id: 'sunquan', stay: true }],
    ['shu', 'chengdu', 30000, 'Liu Zhang', 2, { id: 'liuzhang', stay: true }],
    ['liang', 'changan', 20000, 'Ma Teng', 3, { id: 'mateng', stay: true }],
  ],
  wars: [['cao', 'yuan']],
  allies: [['jing', 'liu']],
  cards: [
    {
      id: 'wuchao', at: 0, title: 'The grain at Wuchao', art: 'raid',
      text: 'Xu You, an old friend of yours and an adviser of Yuan Shao, has deserted to your camp in the night. He says Yuan Shao’s grain for the whole army lies at Wuchao, lightly guarded. Your own grain is nearly gone.',
      options: [
        { label: 'Lead the night raid yourself', fx: { chance: 0.75, win: { sides: { yuan: { will: -25 } }, then: (s) => { if (s.armies.yuanshao) s.armies.yuanshao.men = Math.round(s.armies.yuanshao.men * 0.55); }, log: 'Cao Cao burns the grain at Wuchao; Yuan Shao’s army falls apart' }, lose: { men: -5000, log: 'The raid is a trap: Cao Cao barely escapes' } }, hint: 'Trust a traitor with your life' },
        { label: 'Distrust him', fx: {}, hint: 'And go on starving' },
      ],
      pick: 0, advise: 0,
      history: 'Cao Cao believed Xu You, led 5,000 men through the night in Yuan Shao’s colours, and burned the depot at Wuchao. Yuan Shao’s generals defected and his army broke.',
    },
    {
      id: 'brothers', at: 2, if: (q) => q.alive('yuan'), title: 'The Yuan brothers', art: 'court',
      text: 'Yuan Shao is dead. His sons Yuan Tan and Yuan Shang hate each other. Your strategist Guo Jia says: press them and they will unite; leave them alone and they will tear each other apart.',
      options: [
        { label: 'Wait, and let them quarrel', fx: { sides: { yuan: { will: -15 } }, gold: 30 }, hint: 'Patience, then pick up the pieces' },
        { label: 'Strike at once', fx: { morale: 10, sides: { yuan: { will: 8 } } }, hint: 'Give them a common enemy' },
      ],
      pick: 0, advise: 0,
      history: 'Cao Cao followed Guo Jia’s advice and withdrew; the brothers went to war with each other. When he came back, he took them apart one at a time.',
    },
    {
      id: 'huanggai', from: 4, until: 5, if: (q) => q.war('cao', 'wu') && q.fleet !== 0, title: 'Huang Gai’s letter', art: 'war',
      text: 'Your great fleet faces the allied fleet of Sun Quan and Liu Bei across the Yangtze at the Red Cliffs. Your northern soldiers are seasick and many are ill. Now Huang Gai, a veteran officer of Wu, writes that he will come over to you with his ships.',
      options: [
        { label: 'Accept his surrender', fx: { chance: 0.25, win: { sides: { wu: { will: -25 } }, log: 'Huang Gai’s surrender is real: the allied fleet breaks up' }, lose: { men: -0.35, fleet: 0, will: -12, log: 'Huang Gai’s ships are fire ships: the wind carries them into your fleet, and the flames spread to the camp on shore' } }, hint: 'A gift from heaven, or a trick' },
        { label: 'Suspect a trick, and keep your ships apart', fx: { chance: 0.6, win: { sides: { wu: { will: -8 } }, log: 'The fire ships burn harmlessly on the river' }, lose: { men: -0.15, log: 'Sickness spreads through the camp all the same' } }, hint: 'Caution on strange water' },
      ],
      pick: 0, advise: 1,
      history: 'Cao Cao accepted. Huang Gai’s ships, filled with dry reeds and oil, were set alight as they approached; the wind drove them into Cao Cao’s fleet. Ships and camp burned, and Cao Cao retreated north, his army wasted by fire and disease.',
    },
    {
      id: 'king', at: 9, title: 'King of Wei', art: 'crowned',
      text: 'Your officers want the emperor to make you King of Wei: a title no one outside the imperial family has held. Your rivals say it shows you mean to take the throne.',
      options: [
        { label: 'Accept the title', fx: { will: 10, sides: { wu: { will: 5 }, liu: { will: 5 } } }, hint: 'Honour for your house; your rivals call you a usurper' },
        { label: 'Stay the emperor’s minister', fx: { will: -4 }, hint: 'Modesty, and weaker loyalty' },
      ],
      pick: 0, advise: 0,
      history: 'Cao Cao became King of Wei in 216, but never took the throne himself: “If heaven wills it, let me be King Wen of Zhou,” the father of a founding emperor.',
    },
    {
      id: 'chicken', from: 10, if: (q) => q.owns('cao', 'hanzhong') && q.war('cao', 'liu'), title: 'Chicken ribs', art: 'siege',
      text: 'Liu Bei has come for Hanzhong. Your men are cut off in the mountains, and supplies come over terrible roads. When asked for the night’s password you said only: “chicken ribs”.',
      options: [
        { label: 'Withdraw from Hanzhong', fx: { give: ['hanzhong', 'liu'], morale: 10 }, hint: 'Little meat on those bones' },
        { label: 'Hold it at all costs', fx: { gold: -60, will: -6 }, hint: 'A pity to throw it away' },
      ],
      pick: 0, advise: 0,
      history: 'Cao Cao’s officer Yang Xiu understood the password: chicken ribs have little meat, but it is a pity to throw them away. Cao Cao withdrew from Hanzhong in 219, and had Yang Xiu executed.',
    },
  ],
  events: [
    { id: 'yuanshao', at: 1, if: (q) => q.alive('yuan') && q.living('Yuan Shao'), side: 'yuan', fx: { will: -15, ai: 'cautious', kill: 'Yuan Shao', succeed: { 'Yuan Shao': ['Yuan Tan', 2] }, leader: 'Yuan Tan and Yuan Shang, his quarrelling sons' }, text: 'Yuan Shao dies of an illness; his sons fight over his inheritance', sides: ['yuan'] },
    {
      id: 'jing', at: 4, if: (q) => q.alive('jing') && !q.war('cao', 'jing'), side: 'jing', sides: ['jing', 'cao', 'liu', 'wu'],
      text: 'Liu Biao dies; his son surrenders Jing province to Cao Cao. Liu Bei flees south and joins Sun Quan against him',
      fx: { give: [['xiangyang', 'cao'], ['jiangling', 'cao'], ['changsha', 'liu']], remove: 'liubiao', kill: 'Liu Biao', then: (s) => { s.sides.jing.alive = false; s.sides.cao.fleet = 2; }, rel: [['liu', 'wu', 'ally'], ['cao', 'wu', 'war'], ['cao', 'liu', 'war']], free: ['liubei', 'zhouyu', 'sunquan'] },
    },
    { id: 'plague', at: 5, if: (q) => q.war('cao', 'wu'), fx: { then: (s) => { for (const a of Object.values(s.armies)) if (a.side === 'cao' && ['jiangling', 'xiangyang', 'chibi', 'hefei'].includes(a.at)) a.men = Math.round(a.men * 0.8); } }, text: 'Sickness spreads through the northern soldiers in the wet south', sides: ['cao'] },
    { id: 'mateng', at: 6, if: (q) => q.alive('liang') && q.living('Ma Teng'), side: 'liang', fx: { kill: 'Ma Teng', succeed: { 'Ma Teng': ['Ma Chao', 4] }, leader: 'Ma Chao and Han Sui' }, text: 'Ma Teng, held at your court, pays with his life for his son’s revolt; Ma Chao leads the horsemen of Liang', sides: ['liang'] },
    { id: 'guojia', at: 3, side: 'cao', fx: { kill: 'Guo Jia' }, text: 'Guo Jia, your wisest strategist, dies of an illness on the way back from the north, at thirty-seven', sides: ['cao'] },
    { id: 'zhouyu', at: 6, if: (q) => q.alive('wu') && q.living('Zhou Yu'), side: 'wu', fx: { kill: 'Zhou Yu', succeed: { 'Zhou Yu': ['Lu Su', 3] } }, text: 'Zhou Yu, the victor of the Red Cliffs, dies of an illness at thirty-five; Lu Su takes his command', sides: ['wu'] },
    { id: 'xunyu', at: 7, side: 'cao', fx: { kill: 'Xun Yu' }, text: 'Xun Yu, who opposed your new titles, dies at Shouchun; some say you sent him an empty food box', sides: ['cao'] },
    { id: 'tongpass', at: 6, if: (q) => q.alive('liang'), side: 'liang', fx: { rel: [['liang', 'cao', 'war']], free: ['mateng'] }, text: 'Ma Chao and Han Sui rise in the north-west', sides: ['liang'] },
    { id: 'shu', at: 8, if: (q) => q.alive('shu') && q.alive('liu') && q.owns('shu', 'chengdu'), fx: { give: [['chengdu', 'liu'], ['badong', 'liu']], remove: 'liuzhang', spawn: ['liu', 'chengdu', 30000, 'Zhuge Liang', 5, { id: 'zhuge' }] }, text: 'Liu Zhang surrenders Chengdu to Liu Bei, who makes the rich west his own', sides: ['liu', 'shu'] },
    { id: 'lumeng', at: 10, if: (q) => q.owns('liu', 'jiangling') || q.owns('liu', 'changsha'), fx: { give: [['jiangling', 'wu'], ['changsha', 'wu']], rel: [['liu', 'wu', 'war']] }, text: 'Lü Meng of Wu seizes Jing province from Liu Bei behind Guan Yu’s back', sides: ['wu', 'liu'] },
  ],
};
